### ISSUE TITLE
PaginationLink

### ISSUE THREAD

**Issue by Torwori** [react-bootstrap/react-router-bootstrap#100]
Curently react-bootstrap.Pagination creates a bunch of links which all point to #. I need those links to point to actual pages (primarily for SEO reasons), so I thought I'd make the functionality myself and send you a pull request. Ideally (for my case), such a component would be used like this:
```
<PaginationLink to=... params=... query=.../>
```
where the page param/query would be automatically set by the component itself.
The issue I'm having is that Pagination uses PaginationButton internally, which is why I can't simply toss in a LinkMixin and call it a day.

Any idea how I could tackle this?

**Comment by taion** [comment]
For `href`s in general, I would patch `Pagination` and `PaginationButton` to take e.g. a `hrefFunc` prop (find a better name for this) and use that to calculate the `href` for each `PaginationLink` rather than `onSelect` if specified.

For your case, I'd patch `Pagination` such that you could specify a different class for the pagination buttons, and go from there.

**Comment by Torwori** [comment]
Thanks for the advice. :)
So there is no way it could be implemented without changing `PaginationButton`?
For example, `ButtonLink` doesn't touch the source of `Button`.

**Comment by taion** [comment]
It might be possible to do this without touching those components, but I think it'll be easier/clearer/better if you do modify them to be more extensible, and I'd much rather we implement things that way.

You essentially need to replace the `SafeAnchor` in `PaginationButton`.

**Comment by Torwori** [comment]
Understood. :+1:

**Comment by taion** [comment]
Why close this issue? Did you already code it up that quickly? :D

**Comment by Torwori** [comment]
I'm preparing a pull request for react-bootstrap, we can continue the discussion there. :D

**Comment by Torwori** [comment]
Here it is!
https://github.com/react-bootstrap/react-bootstrap/pull/1052
