### ISSUE TITLE
Router with Redux

### ISSUE THREAD

**Issue by blanchma** [react-bootstrap/react-router-bootstrap#106]
Sorry, I'm kinda noob with Redux and I want to use react-router-boostrap with it but I can't figure out how to make this two work together. The router example is:

var routes = (
  <Route handler={App} path="/">
    <Route name="destination" path="destination/:someparam" handler={Destination} />
  </Route>
);

Router.run(routes, function (Handler) {
  React.render(<Handler/>, document.body);
});

But Redux need to wrap the Handler in a Provider tag like this:

        <Provider store={store}>
          {() =>
            <Router history={this.props.history}>
              <Route path='/' component={App}>
                <Route path='/:login/:name'
                       component={RepoPage} />
                <Route path='/:login'
                       component={UserPage} />
              </Route>
            </Router>
          }
        </Provider>

Source: https://github.com/rackt/redux/blob/master/examples/real-world/containers/Root.js

So, not sure how to merge both ideas.

**Comment by taion** [comment]
I'm not sure how this relates to react-router-bootstrap. Your examples don't show any of the react-router-bootstrap components.
