### ISSUE TITLE
Scope support / class names replacement

### ISSUE THREAD

**Issue by cusspvz** [react-bootstrap/react-router-bootstrap#109]
Is there a way to provide an object with classnames?

We will gonna need to apply different versions of styling, which will require us to use `css-loader` [scope feature](https://github.com/webpack/css-loader#local-scope).

As so, is there a way to configure classes being used by this module on `require`?

**Comment by taion** [comment]
That's not the way that feature works. When you do e.g. `import styles from '../styles/myComponent.css';`, the things you get like `styles.foo` are just strings.

**Comment by cusspvz** [comment]
I know, it returns an object with exchanged generated strings.
Seems that I got mistaken on the repo again. This is related with `react-bootstrap`.

react-bootstrap/react-bootstrap#1207
