### ISSUE TITLE
create branch for tracking react-router@1.0.0-beta4

### ISSUE THREAD

**Issue by ameensol** [react-bootstrap/react-router-bootstrap#113]
I have a [branch](https://github.com/ameensol/react-router-bootstrap/tree/react-router-1.0.0-beta4) I'm working on to fix some of the bugs for myself -- changing context.router  to context.history, etc...

Happy to send PRs to a branch for this here so I can collaborate with others who have similar issues.

**Comment by taion** [comment]
Done: https://github.com/react-bootstrap/react-router-bootstrap/tree/react-router-1.0.0-beta4
