### ISSUE TITLE
v0.19.0 is not published to npm

### ISSUE THREAD

**Issue by ianwremmel** [react-bootstrap/react-router-bootstrap#116]

**Comment by taion** [comment]
It clearly is https://www.npmjs.com/package/react-router-bootstrap

Clean your cache

**Comment by ianwremmel** [comment]
That sort of fixed it, but it looks like the built files aren't there. After I do an install, all I get is 
- CHANGELOG.md 
- README.md    
- package.json

**Comment by ianwremmel** [comment]
oh, wait; ignore that. I think it's because I had the giturl in my package.json
