### ISSUE TITLE
0.19.0 LinkContainer doesn't seem to work with MenuItem

### ISSUE THREAD

**Issue by zybreak** [react-bootstrap/react-router-bootstrap#117]
Versions:
* react-router 1.0.0-rc1
* react-router-bootstrap 0.19.0
* react-bootstrap 0.25.2

The LinkContainers onClick callback is not being fired when wrapping a MenuItem

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-router-bootstrap/issues/112
