### ISSUE TITLE
Needs updating for react-router 1.0

### ISSUE THREAD

**Issue by joewood** [react-bootstrap/react-router-bootstrap#118]
The current version doesn't work with the new API for react-router.

**Comment by taion** [comment]
Yes it does. I'm using it with `react-router@1.0.0-rc1` in my projects and it works fine.

**Comment by joewood** [comment]
I see the error `TypeError: Cannot read property 'context' of null(…)` when using `NavItemLink`. I assumed it was trying to access context to get hold on the history to do the navigation.

Looking at the code, I think I should just be using the `LinkContainer`.

**Comment by taion** [comment]
`NavItemLink` no longer exists in the current release.
