### ISSUE TITLE
NavDropDown Linked MenuItem causes page transition

### ISSUE THREAD

**Issue by NinjaBanjo** [react-bootstrap/react-router-bootstrap#119]
Using this in the react template, the routes exist and the page navigates, but it's a new pageLoad instead of using .pushState;

Debugging, it doesn't appear to even make it to the call to ReactRouter.Link.handleClick
```
 <NavDropdown title="Users" id="nav-users-dropdown">
          <LinkContainer to="/users/create">
            <MenuItem>Create</MenuItem>
          </LinkContainer>
          <LinkContainer to="/users/list">
            <MenuItem>List</MenuItem>
          </LinkContainer>
        </NavDropdown>
```

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-router-bootstrap/issues/112#issuecomment-140436937
