### ISSUE TITLE
Does not work with react 0.14.0, react-bootstrap 0.27.3

### ISSUE THREAD

**Issue by ZiCog** [react-bootstrap/react-router-bootstrap#132]
This:

    import LinkContainer from 'react-router-bootstrap';
    ...
                <LinkContainer to="/login" query={{bar: "baz"}}>
                    <Button  bsSize='small' bsStyle={bsStyle()} >
                        {this.props.lable}
                    </Button>
                </LinkContainer>

produces this:

    { [Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a   class/function (for composite components) but got: undefined. Check the render method of `ButtonWithLed`.] framesToPop: 1 }

**Comment by taion** [comment]
You're importing it wrong.

**Comment by ZiCog** [comment]
Ah, so I am. Should be:

    import { LinkContainer } from 'react-router-bootstrap';

Works a treat. Thanks.
