### ISSUE TITLE
update package.json to depend on react-router v1.0.0 final

### ISSUE THREAD

**Issue by lefant** [react-bootstrap/react-router-bootstrap#133]
hi!

react-router seems to have released 1.0.0: https://github.com/rackt/react-router/releases/tag/v1.0.0

sadly npm thinks that "react-router": ">=1.0.0-rc3" is not satisfied by installing react-router@1.0.0

please bump the dependency to accept 1.0.0

**Comment by jquense** [comment]
I think you might have a different issue the Ranger definitely does match the 1.0.0, you can even confirm using the npm semver calculator

**Comment by taion** [comment]
Right - this shouldn't be causing issues.
