### ISSUE TITLE
Some questions on performance

### ISSUE THREAD

**Issue by alexciarlillo** [react-bootstrap/react-router-bootstrap#135]
Has anyone else noticed that the performance of LinkContainer is rather poor? I have a table with 460 items. Each item has an edit link wrapped in a LinkContainer. For some reason LinkContainer was 1) Rendering twice as many times as there were elements. 2) Each render was taking ~1.4ms totaling about 1310ms of total time spend rendering LinkContainers (based on Perf.printExclusive). 

I then tested just wrapping my buttons in a regular react-router Link component. Time spent rendering was 36ms (0.07ms per component). 

~~Lastly, after testing the above the behavior seems essentially the same as LinkContainer. Is there any reason to use LinkContainer when you can just wrap react-bootstrap components in a Link?~~ I see now that LinkContainer is still useful when wrapping components like NavItem.

**Comment by taion** [comment]
If you just have a plain anchor, you shouldn't be using `<LinkContainer>`. For things like `<Button>`, `<LinkContainer>` is the intended solution. You can compare the implementations though - they're almost the same and I'm not sure why you'd be seeing performance issues.

**Comment by alexciarlillo** [comment]
Yes I was using a <Button> from react-bootstrap. Wrapping a <Button> in a plain <Link> seems to work fine though. 

I will take a stab at diagnosing what I am seeing in regards to performance when I get a chance. I just wanted to see if there was any obvious reasoning to what I was seeing before going down the rabbit hole.

**Comment by Ognian** [comment]
I have the perf problem too. 
LinkContainer Instances are 3 times as high as they should be.
I looked at the source, but  I have no idea what goes wrong. Maybe calling react.cloneElement in render is not such a good idea?

**Comment by taion** [comment]
Stop trying to profile your apps without `NODE_ENV` set to `production`.

**Comment by Ognian** [comment]
Sorry, but if NODE_ENV is set to ```production```Perf.printExclusive() or Pef.printInclusive()  contains no rows. What am I doing wrong?
