### ISSUE TITLE
history createHref query argument is now deprecated

### ISSUE THREAD

**Issue by kromit** [react-bootstrap/react-router-bootstrap#136]
After History update the console is full with this warning:

*the query argument to createHref is deprecated; use a location descriptor instead*

The warning is caused by [this](/react-bootstrap/react-router-bootstrap/blob/master/src/LinkContainer.js#L37) call

**Comment by taion** [comment]
Respect the peer dep on the Router.

**Comment by kromit** [comment]
I do

https://github.com/rackt/react-router/blob/master/package.json#L44

**Comment by taion** [comment]
That's not the peer dep for the 1.0.2 release.

**Comment by kromit** [comment]
Yes, but this does not make this ticket less valid, or will you reopen it when 1.0.3 is released? :alarm_clock:

**Comment by taion** [comment]
No, I'll just fix this the same way I fixed Link upstream.
