### ISSUE TITLE
peerDependency invalid on npm2

### ISSUE THREAD

**Issue by bdefore** [react-bootstrap/react-router-bootstrap#137]
react-router is now version 1.0.2 and your peerDependency of `react-router@>=1.0.0-rc3` is invalid with npm 2 due to how it handles pre-release versioning: https://github.com/npm/npm/issues/8854

I suggest updating it to `react-router@>=1.0.0`

**Comment by taion** [comment]
You have it inverted. The issue there is that e.g. `1.1.0-rc` won't satisfy `>= 1.0.0`. However `1.0.2` satisfies `>= 1.0.0-rc3` just fine. I'd accept a PR to fix it but I'm not cutting a new release for this.

**Comment by bdefore** [comment]
Ah ok, thanks @taion
