### ISSUE TITLE
react-router 1.15.0 deprecates history.pushState, changes query argument in createHref

### ISSUE THREAD

**Issue by k-sheth** [react-bootstrap/react-router-bootstrap#138]
I just upgraded to react-router 1.15.0, I am using react-router-bootstrap 0.19.x. 

I get warnings as below - 

Warning: [history] pushState is deprecated; use push instead
warning @ browser.js?26d3:49
(anonymous function) @ deprecate.js?56ef:13
handleClick @ Link.js?8240:95
onClick @ LinkContainer.js?00ea:50

Warning: the query argument to createHref is deprecated; use a location descriptor instead
warning @ browser.js?26d3:49
createHref @ useQueries.js?d176:128
render @ LinkContainer.js?00ea:71

**Comment by taion** [comment]
Respect the React Router peer dep range.
