### ISSUE TITLE
Cannot set activeClassName

### ISSUE THREAD

**Issue by mmahalwy** [react-bootstrap/react-router-bootstrap#139]
Can on Link for react-router, cannot here

**Comment by taion** [comment]
That's intentional, this is just for wrapping our React-Bootstrap components. Do whatever you'd normally do if you weren't using the router link stuff.

**Comment by rbalicki2** [comment]
Could you provide an example of how to set a different activeClassName using react-router-bootstrap components? Unfortunately, bootstrap styles .active a pretty specifically, and I'd like to change .active to a different class in order to avoid fighting with bootstrap.

**Comment by taion** [comment]
You can't do it at the level of this library. The design intention is that the underlying component owns its active styling, not the container; all the container does is pass down an `active` prop. You'll most likely just need to override the CSS in this case.
