### ISSUE TITLE
doesn't play nice with Breadcrumb

### ISSUE THREAD

**Issue by TrejGun** [react-bootstrap/react-router-bootstrap#141]
Hi!

I have found a small issue
```js
<Breadcrumb>{this.props.routes.map((item, i) =>
	<LinkContainer key={i} to={item.path}>
		<BreadcrumbItem>
			{item.component.displayName}
		</BreadcrumbItem>
	</LinkContainer>
)}</Breadcrumb>
```
this code shows warning in console

```
Warning: [react-bootstrap] `href` and `active` properties cannot be set at the same time
```

and all links are inactive

also can you please add this example to visual tests

**Comment by taion** [comment]
This is an upstream issue with the breadcrumb component. If you want this in the visual tests, make a PR.

**Comment by jquense** [comment]
is this upstream? the upstream behavior is not a bug persay...I guess it makes most sense to fix it there tho?

**Comment by taion** [comment]
There's not really anything we can do in `<LinkContainer>`... doesn't make sense to drop the `href` when active here.

**Comment by jquense** [comment]
hmm yeah I agree ok. fair enough!
