### ISSUE TITLE
routerWillLeave() called 3 times when canceling navigation

### ISSUE THREAD

**Issue by rodryquintero** [react-bootstrap/react-router-bootstrap#143]
When using the routerWillLeave nav hook, when click on cancel the method will be called 3 times, showing the dialong confirmation 3 times.

**Comment by taion** [comment]
You've accidentally attached multiple leave hooks. Don't do that.

**Comment by rodryquintero** [comment]
I have not. There is only one leave hook on the container component. Not sure why this is called multiple times.

``` 
routerWillLeave(nextUrl) {

    if (this.props._hasChanged) {
      return 'You have unsaved information, are you sure you want to leave this page?';
    }
  },
```

Perhhaps some documentation/examples on how to use with the different Bootstrap components. I am using it on NavItem for a header and will use it on other navitems.

```
      return  <LinkContainer key={i} to={to}>
                <NavItem
                eventKey={id}
                >
                <i className={iconClass}></i>&nbsp;
                {intl.messages[label]}
                </NavItem>
            </LinkContainer>;

```

Thanks.

**Comment by taion** [comment]
You probably have multiple of those containers in your component tree.

**Comment by rodryquintero** [comment]
Well, not really since I was first trying out the `routerWillLeave()` hook on that one component. I even had to rewrite it using `React.createClass` since I was using all ES6 style components.

I think this is more of an issue with `react-router` than with the `<LinkContainer/>`. The react-router guys say the reason for this behaviour is not using their `<Link>` components for links.

I will take this to the `react-router` issues page.

**Comment by jquense** [comment]
@taion will probably the person who answers the issue there as well :P. I have also used both this and my own Link implementation and haven't seen this issue so you may just be overlooking something in your code.

**Comment by rodryquintero** [comment]
Perhaps you can post an example that I can use?

**Comment by taion** [comment]
React Router has a "transitions" example that demonstrates leave hooks. You probably have multiple components mounted that try to attach leave hooks.

**Comment by jquense** [comment]
even still doesn't the routerWillLeave stop firing the hooks once one returns true? That may be unrelated....

**Comment by taion** [comment]
Huh, you're right. Not sure what's going on, then.

**Comment by rodryquintero** [comment]
I figured out what happened with this issue. It is related to the `history` lib. Turns out I was using `window.location` for navigating through the application. I changed all the navigation links to use `history.pushState` and the problem was solved. I don`t event need to use the `LinkContainer` component anymore, apparently :).

Thanks for all the help.
