### ISSUE TITLE
[LinkContainer] [NavItem] Uncaught TypeError: Cannot read property 'pushState' of undefined

### ISSUE THREAD

**Issue by BerndWessels** [react-bootstrap/react-router-bootstrap#146]
Hello

I try to get this working:

                <Nav>
                  <LinkContainer to={`/users`}>
                    <NavItem>Users</NavItem>
                  </LinkContainer>
                </Nav>

Even this doesn't work:

            <LinkContainer to={`/users`}>
              <Button>Foo</Button>
            </LinkContainer>

I get `Uncaught TypeError: Cannot read property 'pushState' of undefined` when I click on the item:

![react-router-bootstrap-01](https://cloud.githubusercontent.com/assets/1776695/12106259/48d883b2-b3c2-11e5-84a4-ba541303e2cb.jpg)

Clicking on the 'normal' `Link` in that component works just fine:

    <Link to={`/users`} activeClassName="active">Users</Link>

![react-router-bootstrap-02](https://cloud.githubusercontent.com/assets/1776695/12106317/ec848fec-b3c2-11e5-8c6c-14a077d2c275.jpg)

So the problem must be with the `LinkContainer` I guess.

Is this a bug or am I doing something wrong?

I use these package versions:

    "dependencies": {
      "bootstrap": "^3.0.0",
      "history": "1.13.1",
      "lodash": "^3.0.0",
      "mysql": "^2.0.0",
      "react": "^0.14.0",
      "react-bootstrap": "^0.28.0",
      "react-dom": "^0.14.0",
      "react-relay": "^0.6.0",
      "react-router": "^1.0.0",
      "react-router-bootstrap": "^0.20.0",
      "react-router-relay": "^0.8.0",
      "sequelize": "^3.0.0"
    },

And this is my app component:

    import React from 'react';
    import Relay from 'react-relay';
    import {Link} from 'react-router';
    import { Nav, Navbar, NavbarBrand, NavItem, NavDropdown, MenuItem } from 'react-bootstrap';
    import { LinkContainer } from 'react-router-bootstrap';
    
    class App extends React.Component {
      // Expected properties.
      static propTypes = {
        viewer: React.PropTypes.object.isRequired,
        children: React.PropTypes.node.isRequired
      };
      // Initialize the component.
      constructor(props) {
        super(props);
      }
    
      // Render the component.
      render() {
        // Get the properties.
        const {viewer, children} = this.props;
        // Return the component UI.
        return (
          <div>
            <Navbar inverse>
              <Navbar.Header>
                <Navbar.Brand>
                  <a href="#">React-Webpack</a>
                </Navbar.Brand>
                <Navbar.Toggle />
              </Navbar.Header>
              <Navbar.Collapse>
                <Nav>
                  <LinkContainer to={`/users`}>
                    <NavItem>Users</NavItem>
                  </LinkContainer>
                </Nav>
              </Navbar.Collapse>
            </Navbar>
            <Link to={`/users`} activeClassName="active">Users</Link>
            {children}
          </div>
        );
      }
    }
    
    /**
     * The data container.
     */
    export default Relay.createContainer(App, {
      fragments: {
        viewer: () => Relay.QL`
              fragment on Person {
                id
              }
            `
      }
    });

**Comment by BerndWessels** [comment]
OK, no worries - I got the wrong package versions.

    "react-router": ">=2.0.0-rc2",
    "react-router-bootstrap": "^0.20.0",
    "react-router-relay": "^0.9.0",

Works just fine.

**Comment by SpencerCDixon** [comment]
@BerndWessels did you just need to upgrade to react-router 2.0? I just started getting this issue to

**Comment by SpencerCDixon** [comment]
nvm that totally fixed it upgrading to 2.0

**Comment by BerndWessels** [comment]
glad that this was helpful.

**Comment by SpencerCDixon** [comment]
:+1:
