### ISSUE TITLE
not working with latest version

### ISSUE THREAD

**Issue by Kepro** [react-bootstrap/react-router-bootstrap#149]
Hi i have
    "react-router": "^2.0.0-rc4",
    "react-router-bootstrap": "^0.20.1",

i get a error
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Header`.

my code is 

````
import LinkContainer from 'react-router-bootstrap';

<LinkContainer to="/invoice">
                <Button>Faktúry</Button>
</LinkContainer>
````

also any configuration of LinkContainer i get same error

**Comment by jquense** [comment]
`import { LinkContainer } from 'react-router-bootstrap';`
