### ISSUE TITLE
LinkContainer with NavItem

### ISSUE THREAD

**Issue by borovik96** [react-bootstrap/react-router-bootstrap#151]
When i use LinkContainer with NavItem first Item always active.
![image](https://cloud.githubusercontent.com/assets/9018702/12923715/cd31b726-cf67-11e5-992c-997cec3c17ab.png)

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/master/docs/guides/basics/IndexRoutes.md

**Comment by borovik96** [comment]
@taion Thanks

**Comment by alexbooker** [comment]
@taion Link is dead.

**Comment by alexbooker** [comment]
I think this is the updated link: https://github.com/reactjs/react-router/blob/master/docs/guides/IndexRoutes.md

**Comment by alexbooker** [comment]
I am using an `IndexRoute` and still experience the behaviour described by @borovik96:

![](http://i.imgur.com/mSZjoxY.png)

**Comment by alexbooker** [comment]
The problem is that I was using a `LinkContainer` for the _Home_ menu item when I should have been using `IndexLinkContainer`!

You can import `IndexLinkContainer` from `react-router-bootstrap` like so:

```js
import { IndexLinkContainer } from 'react-router-bootstrap'
```

... And use it like this:

```jsx
<Nav>
  <IndexLinkContainer to="/" activeClassName="active">
    <NavItem>Home</NavItem>
  </IndexLinkContainer>
  <LinkContainer to="/about" activeClassName="active">
    <NavItem>About</NavItem>
  </LinkContainer>
</Nav>
```

**Comment by elcojacobs** [comment]
I spent quite some time debugging before I realized I was importing `IndexLinkContainer` from `react-router` instead of `react-router-bootstrap`. Maybe this comment will save others some time.

**Comment by clearly** [comment]
If i use this exact code I get a `Uncaught TypeError: Cannot read property 'getHostNode' of null` if I click on the items. Any ideas what that might be?

**Comment by osaesm** [comment]
I used the same code as @mattbajorek and got ```TypeError: Cannot read property 'history' of undefined```. Completely lost

**Comment by v12** [comment]
@osaesm what versions of react-router, react-bootstrap and react-router-bootstrap do you use?

**Comment by osaesm** [comment]
react-router: v4
react-bootstrap: 0.32.0
react-router-bootstrap: 0.24.4

**Comment by aytekinyaliz** [comment]
the following configuration works for me. you can also use active={null}.
<Nav>
   <LinkContainer to="/customers" active={undefined}>
      <NavItem>Customers</NavItem>
   </LinkContainer>
   <LinkContainer to="/resources" active={undefined}>
      <NavItem >Resources</NavItem>
   </LinkContainer>
</Nav>

**Comment by w3jimmy** [comment]
(This solution does not use IndexLinkContainer) 
By default LinkContainer shows links active for any matching substring of the current route.
If your current url is "/about/team" and your links are "/about" and "/about/team" then both links will show active. To prevent this, you need to add `exact` attribute to the LinkContainer.

**Comment by rlogwood** [comment]
At this time, <LinkContainer ... exact> appears to be equivalent to <IndexLinkContainer ...>

[react-router-bootstrap/src/IndexLinkContainer.js snip](https://github.com/react-bootstrap/react-router-bootstrap/blob/master/src/IndexLinkContainer.js)
```javascript
export default class IndexLinkContainer extends React.Component {
  render() {
    return (
      <LinkContainer {...this.props} exact />
    );
  }
```

And FWIW currently Nav.Link has class nav-link, so you can get a hover effect as shown:
```javascript
<LinkContainer  to="/" exact activeClassName='(my selected class)' className='(my menu item class)'>
    <Nav.Link>Home</Nav.Link>
</LinkContainer>
```

```css
a.nav-link:hover {
    cursor: pointer;
    background:linen;
    font-weight: bold;
    font-style: italic;
}
```

**Comment by jakub-mroz** [comment]
> ```js
> IndexLinkContainer
> ```

Had the same problem. Always read doc... something we dev never do :D LOL
