### ISSUE TITLE
Active class only set when doing a full page refresh

### ISSUE THREAD

**Issue by olalonde** [react-bootstrap/react-router-bootstrap#152]
For some reason, when I click NavItems in my header everything works as expected (the URL changes) but the `active` class is not updated unless I do a full page refresh. Using `react-router`'s Link component works as expected though.

```
"react-bootstrap": "^0.28.2",
"react-router-bootstrap": "^0.20.1",
"react-router-redux": "^3.0.0",
```

**Comment by taion** [comment]
Works fine for me. Do you have a repro?

**Comment by olalonde** [comment]
Weird, activeClassName doesn't seem to be doing anything either. :(

**Comment by olalonde** [comment]
Here's my header file:

```javascript
import React from 'react'
import { LinkContainer } from 'react-router-bootstrap'
import { connect } from 'react-redux'
import {
  Nav,
  Navbar,
  NavItem,
  MenuItem,
} from 'react-bootstrap'

export default connect()(class extends React.Component {
  constructor(props) {
    super(props)
  }

  render() {
    return (
      <Navbar>
        <Navbar.Header>
          <Navbar.Brand className="nav-logo">
            <LinkContainer to="/">
              <a href="/"><img src="/logo.png" alt="Blockai logo" /></a>
            </LinkContainer>
          </Navbar.Brand>
          <Navbar.Toggle />
        </Navbar.Header>
        <Navbar.Collapse>
          <Nav pullLeft>
            <LinkContainer to="/product">
              <NavItem>Product</NavItem>
            </LinkContainer>
            <LinkContainer to="/pricing" activeClassName="none">
              <NavItem>Pricing</NavItem>
            </LinkContainer>
            <LinkContainer to="/faq" activeClassName="none">
              <NavItem eventKey={3}>FAQ</NavItem>
            </LinkContainer>
          </Nav>
          <Nav pullRight>
            <LinkContainer to="auth/login" activeClassName="none">
              <NavItem eventKey={4}>Login</NavItem>
            </LinkContainer>
            <LinkContainer to="auth/signup" activeClassName="none">
              <MenuItem eventKey={5}>Sign Up</MenuItem>
            </LinkContainer>
          </Nav>
        </Navbar.Collapse>
      </Navbar>
    )
  }
})
```

**Comment by olalonde** [comment]
Ohhh... removing the connect() and naming the class fixed the problem :P

**Comment by taion** [comment]
Use `pure: false`.

**Comment by themeteorchef** [comment]
Howdy. I'm bumping into this as well. Here's a GIF showing the behavior alongside the code. Any thoughts?

![](http://cl.ly/2M072Q3e452n/link-container-bug.gif)

**Comment by taion** [comment]
This is ultimately just https://github.com/reactjs/react-router/issues/470. Work around it however you think best.

**Comment by themeteorchef** [comment]
@taion have been trying a few different things (including fiddling with isActive in context) and nothing is really working. Any hints on a workaround for now?

**Comment by taion** [comment]
Use `pure: false` on your Redux container. That's all. Follow up on the upstream issue as relevant.

**Comment by shawnmclean** [comment]
The readme should probably be updated with this.

**Comment by DarynHolmes** [comment]
Using `pure: false` helped me and this is how to do it - https://github.com/reactjs/react-redux/blob/master/docs/troubleshooting.md

**Comment by hscheckenbacher** [comment]
I ran into this issue just now and I'm using React.PureComponent as a default because of my immutable state. As mentioned before by @taion not using pure makes this work as expected. In my case I had to use React.Component instead of React.PureComponent.

Figured I'd mention this here in case someone else stumbles upon it.

**Comment by abhinaw27392** [comment]
`//import react
import React from 'react';
import { Link } from 'react-router-dom'

// import redux
import { connect } from 'react-redux'

// import third-party
import { IndexLinkContainer, LinkContainer } from 'react-router-bootstrap'
import {
  Nav, Navbar, NavItem,
  NavDropdown, MenuItem
} from 'react-bootstrap'

//import local
import AuthorizedLinkContainer from '../common/hoc/AuthorizedLinkContainer'

import { EMPLOYEE_ROLE, MANAGER_ROLE, ADMIN_ROLE } from '../main/Main'

// import css
import './Header.css'
import './Header.css'
import Logo from './AH_Long.png'

export const HeaderComponent = ({ userData }) => (
  <header>

    <Navbar fluid fixedTop collapseOnSelect>
      <Navbar.Header>
        <div className="navbar-brand">
          <img src={Logo} height="40" />
        </div>
        <Navbar.Toggle />
      </Navbar.Header>
      { userData  ? (
        <Navbar.Collapse>
          <Nav>

            <IndexLinkContainer to="/app" activeHref="active">
              <NavItem>Dashboard</NavItem>
            </IndexLinkContainer>

            <AuthorizedLinkContainer allowedRoles={EMPLOYEE_ROLE} to="/app/timesheet" activeHref="active">
              <NavItem>Timesheet</NavItem>
            </AuthorizedLinkContainer>

            <AuthorizedLinkContainer allowedRoles={MANAGER_ROLE} to="/app/manager" activeHref="active">
              <NavItem>Manage</NavItem>
            </AuthorizedLinkContainer>

            <AuthorizedLinkContainer allowedRoles={ADMIN_ROLE} to="/app/admin" activeHref="active">
              <NavItem>Administer</NavItem>
            </AuthorizedLinkContainer>

          </Nav>

          <Nav pullRight>
            <NavItem ><span>{userData.firstName} {userData.lastName}</span></NavItem>
            <NavItem componentClass="span" eventKey={20} href="#"><Link to="/auth/logout">Logout</Link></NavItem>
          </Nav>

        </Navbar.Collapse>
      ) : null}
    </Navbar>

  </header>
)


const mapStateToProps = state => {
  return state.authenticationReducer.loggedUser
}

// https://github.com/react-bootstrap/react-router-bootstrap/issues/152
const Header = connect(mapStateToProps, null, null, { pure: false })(HeaderComponent);

export default `Header;````

**Comment by flinkenberg** [comment]
Check if your component is re-rendering. React.PureComponent may be the reason why those Navlinks won't re-render.
