### ISSUE TITLE
LinkContainer with NavItem does not seem to work

### ISSUE THREAD

**Issue by olalonde** [react-bootstrap/react-router-bootstrap#158]
```javascript
        <LinkContainer to="/dashboard/monitoring/reports">
          <NavItem>Copyright Watch</NavItem>
        </LinkContainer>
```

The above doesn't set the NavItem to active for the path `/dashboard/monitoring/reports/latest`.

**Comment by taion** [comment]
Which versions are you using?

**Comment by olalonde** [comment]
`0.20.1`

**Comment by taion** [comment]
Your code looks fine and matches what's in the visual test: https://github.com/react-bootstrap/react-router-bootstrap/blob/master/tests/visual/NavItemVisual.js

Do you have a more comprehensive repro available?

**Comment by olalonde** [comment]
Not sure if that helps but here's part of my `routes.js`:

```
      <Route path="monitoring" component={Monitoring.Layout}>
        <IndexRoute component={Monitoring.Analytics} />
        <Route path="analytics/:sha1" component={Monitoring.Analytics} />
        <Redirect from="reports" to="reports/latest" />
        <Route path="reports/:reportId" component={Monitoring.ReportMatches} />
        <Route path="reports/:reportId/:registrationId" component={Monitoring.ReportMatches} />
      </Route>
```

Maybe because my subroutes (e.g. "reports/:reportId") are at the same level as the "reports" route?

I can try to reproduce more accurately if that's not enough.

**Comment by olalonde** [comment]
I'm guessing it's related to that because if I sent my LinkContainer to "/dashboard/monitoring" it works as expected:

```
        <LinkContainer to="/dashboard/monitoring">
          <NavItem eventKey="2">Copyright Watch</NavItem>
        </LinkContainer>
```

**Comment by taion** [comment]
Ah, I see – that's correct. "Active" semantics don't work that way – it needs to be an actual parent route. See https://github.com/reactjs/react-router/issues/3231. I'm planning on fixing this as soon as I can in rrtr, if that's relevant to you.

**Comment by olalonde** [comment]
Oh yeah, that's it...

```
        <Route path="reports">
          <IndexRedirect from="reports" to="reports/latest" />
          <Route path=":reportId" component={Monitoring.ReportMatches} />
          <Route path=":reportId/:registrationId" component={Monitoring.ReportMatches} />
        </Route>
```

fixed the problem. I'll upgrade to rrtr eventually so yep:)

**Comment by taion** [comment]
Yup – note that you don't need `from` on `<IndexRedirect>`, BTW.

**Comment by Emixam23** [comment]
Hey ! So, any update? 

I am still stuck with the NavItem of my navbar....
