### ISSUE TITLE
Move to rrtr breaks build

### ISSUE THREAD

**Issue by tanepiper** [react-bootstrap/react-router-bootstrap#159]
Sorry but PLEASE don't change dependencies on a minor upgrade, you've managed to break our builds.  If you had released this as a 1.0 version it would have been fine, but in moving 0.20 => 0.21 and completely changing the underlying dependency is irresponsible and breaks the semver contract that I can expect no major breakages between minor versions.

```
ERROR in ./~/react-router-bootstrap/lib/LinkContainer.js
Module not found: Error: Cannot resolve module 'rrtr/lib/Link' in D:\Documents\GitHub\app\node_modules\react-router-bootstrap\lib
 @ ./~/react-router-bootstrap/lib/LinkContainer.js 25:19-43
```

**Comment by jquense** [comment]
below `1.0.0` there is no such thing as a "major" change, and according to the semver spec "anything goes" In general though most everyone in the node/npm world follows the "treat the minor point as a major bump until 1.0.0" which is what we are doing here. 

if you are expecting pre 1.0.0 versions to not break on minor bumps you are going to have a bad time in the npm/node world well beyond this package. I would re-evaluate that strategy

**Comment by tanepiper** [comment]
@jquense While I appreciate the point - you have changed a fundamental underlying dependency because someone claimed "react-router is dead" despite the fact there was a release but 16 hours ago.  I've been through plenty of dependency hell and I'm been developing node apps since 0.2 so please don't point to me being ignorant.

You could have forked the project and released rrtr-bootsrap instead if it's such a fundamental change.

So I have two choices, remove your code or fork it and revert it. I'll leave it at that - but I imagine I won't be the only one who brings this change up.

**Comment by taion** [comment]
rrtr is a drop-in replacement for React Router, so you have a third choice – switch from React Router to rrtr.

As @jquense mentioned, the convention is that the left-most non-zero digit in the version string corresponds to breaking changes. This is the behavior enforced by npm caret ranges, so you should not have automatically received this update without manually upgrading.

**Comment by tanepiper** [comment]
@taion @jquense "rrtr is a drop in replacement" - well not quite when your writing software for enterprise - it's an additional cost of replacing and testing that it doesn't break everything.  Especially since it's been out less than a day and is essentially a fork.

Considering the reply I'll happily choose to remove it and continue on the current code path without it.

**Comment by taion** [comment]
I'm re-opening https://github.com/react-bootstrap/react-router-bootstrap/issues/156 for discussion. I'm not committing to anything yet.

**Comment by taion** [comment]
Per #156, this package has been pointed back at `react-router` as of v0.22.0.
