### ISSUE TITLE
React-Router is back?

### ISSUE THREAD

**Issue by MichalKononenko** [react-bootstrap/react-router-bootstrap#162]
In v0.22, you mentioned that you were switching from supporting React-Router to [rrtr](https://github.com/taion/rrtr). However, this package is now deprecated. Is this version compatible with the latest release of React-router as well?

**Comment by taion** [comment]
I switched it all back: https://github.com/react-bootstrap/react-router-bootstrap/issues/156

Stop using rrtr, go back to React Router.

**Comment by jquense** [comment]
is it still deprecated on NPM?

**Comment by taion** [comment]
```
$ npm i rrtr rrtr-bootstrap
npm WARN deprecated rrtr@2.2.2: Use React Router
npm WARN deprecated rrtr-bootstrap@0.21.2: Use React Router and React-Router-Bootstrap
```
