### ISSUE TITLE
NavDropdown not set to active when MenuItem child link is active route 

### ISSUE THREAD

**Issue by jeffhoang** [react-bootstrap/react-router-bootstrap#167]
I also run into a similar issue...

However, my issue is the NavDropdown (see example code below)

```
<LinkContainer to="/products" activeClassName="active">
      <NavDropdown title="Products" id="products-dropdown" noCaret={true}>
      <LinkContainer to="/products/1" activeClassName="active"><MenuItem>Product 1</MenuItem></LinkContainer>
      <LinkContainer to="/products/2" activeClassName="active"><MenuItem>Product 2</MenuItem></LinkContainer>
      <LinkContainer to="/products/3" activeClassName="active"><MenuItem>Product 3</MenuItem></LinkContainer>
     <MenuItem divider />
     <LinkContainer to="/products/major" activeClassName="active"><MenuItem>Major Product</MenuItem></LinkContainer>
     </NavDropdown>
</LinkContainer>
```

Routes (using react-router-bootstrap):

```
<Route path="/" component={App}>
      <IndexRoute component={Home}/>
      <Route path="about" component={About}/>
      <Route path="products/:id" component={Products}/>
      <Route path="contact" component={Contact}/>
      <Route path="login" component={Login}/>
      <Route path="*" component={NotFound} status={404} />
</Route>
```

View 1, selecting a menu item :

![screen shot 2016-05-15 at 1 38 58 pm](https://cloud.githubusercontent.com/assets/2557321/15276628/6a855016-1aa2-11e6-87cd-1feb0dc8ba34.png)

View 2, menu item has been selected and routed to its component accordingly, however, notice "Products" is not set to active.

![screen shot 2016-05-15 at 1 37 19 pm](https://cloud.githubusercontent.com/assets/2557321/15276620/2ebda72c-1aa2-11e6-92db-caec7000c8e0.png)

The parent container of "Products" is never set to active even after a MenuItem has been routed and selected.

Related to this :  https://www.bountysource.com/issues/34064154-active-prop-not-respected-in-navdropdown

**Comment by taion** [comment]
This is just the upstream R-B issue. There's nothing specific to this library to resolve.

**Comment by sverhagen** [comment]
Do we think this would be fixed now? The referenced `react-bootstrap` issue states that this does _not_ solve _this_ issue, and I'm observing that it does, in fact, not work. I am very susceptible having done it wrong, but the issue seems to corroborate my observation.

**Comment by jquense** [comment]
yup it's fixed, can confirm

**Comment by sverhagen** [comment]
Thanks for confirming. I can't get it to work, and I'm seeing a bunch of other funky thinks in regard to the `active` state, but I'm a beginner at React, and I could use some better reference. Do you know of a working example online that showcases this behavior?

**Comment by nicholaslie90** [comment]
I'm also having difficulties in getting this to work myself.

**Comment by sverhagen** [comment]
After some more tinkering, the solution of wrapping the whole menu in a `<LinkContainer/>` somewhat works and may be useful for some. But I now realize that not all of my menus have only menu items with the same router path. So, an more useful implementation would be to just iterate children, determine their state, update the parent accordingly. I've not had any luck building that out, and I'd take some suggestions.

**Comment by manikantag** [comment]
After spending more than a day with writing custom logic to make the `NavDrodown` also active when any of the children item is selected, the actual solution for me is quite simple.

If you are using `react-router-bootstrap` _(which you would have mostly)_, use `LinkContainer` with matching route:

Example:

```jsx
<LinkContainer to="/reports">
    <NavDropdown title="Reports" id="collasible-nav-dropdown">
        <LinkContainer to="/reports/students">
            <NavDropdown.Item>Students report</NavDropdown.Item>
        </LinkContainer>
        <LinkContainer to="/reports/faculty">
            <NavDropdown.Item>Faculty report</NavDropdown.Item>
        </LinkContainer>
    </NavDropdown>
</LinkContainer>
```

`LinkContainer` will now hightlight both main Dropdown title and the actual selected item too

**Comment by scottchow-RL** [comment]
So the problem I have with the solution proposed by @manikantag is that this solution will cause you to navigate to the route when the `NavDropdown` is clicked.

> ```js-jsx
> <LinkContainer to="/reports">
>     <NavDropdown title="Reports" id="collasible-nav-dropdown">
>         <LinkContainer to="/reports/students">
>             <NavDropdown.Item>Students report</NavDropdown.Item>
>         </LinkContainer>
>         <LinkContainer to="/reports/faculty">
>             <NavDropdown.Item>Faculty report</NavDropdown.Item>
>         </LinkContainer>
>     </NavDropdown>
> </LinkContainer>
> ```

**Comment by jerome-diver** [comment]
@scottchow-RL yes sure.

## what i not use
 was to not use this library (and then not overload script files modules)
## what i do instead
1.  skip NavDropdown.Item react-bootstrap tag.

1. use NavLink react-router-dom instead

1. add a css (mine is sass, but anyway, it is same) line to select NavDropdown a to have style: display: block (if not, you will not have link in line)

It works perfectly.

## example for the full working solution
The component file (to be exported then)
```javascript
import React, { Component } from 'react'
import { Navbar, Nav, NavDropdown } from 'react-bootstrap'
import { NavLink } from "react-router-dom"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faUsers, faUserPlus, faUserCircle, faUserTie, 
        faUserEdit, faAddressCard, faFolder, faHome, 
        faSignInAlt} from '@fortawesome/free-solid-svg-icons'

class Navigation extends Component {
  render () {
    return (
      <>
        <Navbar expand="lg" bg="dark" fg="light" fixed="top">
          <Navbar.Brand href="">SourceCodeMaker</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="mr-auto">
              <Nav.Link as={NavLink} to='/' exact activeClassName="menuselected">
                <FontAwesomeIcon icon={faHome}/> Home</Nav.Link>
              <Nav.Link as={NavLink} to='/subjects' activeClassName="menuselected">
                <FontAwesomeIcon icon={faFolder}/> Subjects</Nav.Link>
              <Nav.Link as={NavLink} to='/contacts' activeClassName="menuselected">
                <FontAwesomeIcon icon={faAddressCard}/> Contacts</Nav.Link>
              <Nav.Link as={NavLink} to='/example' activeClassName="menuselected">
                Example</Nav.Link>
              <NavDropdown title={<span><FontAwesomeIcon icon={faUserCircle}/> Users</span>} id="basic-nav-dropdown">
                  <NavLink as={NavLink} to='/signin' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faSignInAlt}/> Sign in</NavLink>
                  <NavLink as={NavLink} to='/signup' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faUserPlus}/> Sign up</NavLink>
                  <NavLink as={NavLink} to='/users' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faUsers}/> Users list</NavLink>
                  <NavLink as={NavLink} to='/profile/:username' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faUserEdit}/> Profile</NavLink>
                  <NavLink as={NavLink} to='/admin' activeClassName='menuselected'>
                  <FontAwesomeIcon icon={faUserTie}/> Admin</NavLink>
              </NavDropdown>
            </Nav>
          </Navbar.Collapse>
        </Navbar>
      </>
    )
  }
}
```
SASS menu part of the concerned file:
```sass
.dropdown-menu
  a
    display: block
```
