### ISSUE TITLE
Active state not updated if clicking link outside NavBar

### ISSUE THREAD

**Issue by olalonde** [react-bootstrap/react-router-bootstrap#168]
I have a weird bug where the navbar link's active state is only updated when I click to a different link from the navbar but won't work if I click a link in the footer for example. I'm not sure if it's a bug with this module or something else.

Update: After removing a custom `onClick` attribute on my LinkContainer, I am getting the expected behaviour. Weird.

**Comment by taion** [comment]
You probably have a pure Redux container somewhere in there.
