### ISSUE TITLE
Include the context fix for the Link

### ISSUE THREAD

**Issue by gaearon** [react-bootstrap/react-router-bootstrap#169]
We can do this either by using Link directly or by using the shared context subscriber package.

**Comment by taion** [comment]
Do you need this for the tutorial you're working on?

**Comment by gaearon** [comment]
No, no rush there. 😄 

Just had this reported to `react-redux` as a bug, I closed it because of 3.0 alpha, but couldn’t figure out why OP says it’s still not fixed. Then realized they used this library.

I’ll likely be mentioning that 3.0 fixes `<Link>` in my talk on Jun 1st so it’d be great if this library contained a fix by the time 3.0 stable is out.

Thanks!

**Comment by josiahsprague** [comment]
Is the context fix the same issue as https://github.com/react-bootstrap/react-bootstrap/issues/1994 ? Just saw @erlgry having an issue with `<LinkContainer />`

**Comment by mbcooper** [comment]
+1

**Comment by v12** [comment]
Closing this issue since there were quite a few changes since it was open (including changes related to context usage). But feel free to reopen if it causes any problems when using the library.
