### ISSUE TITLE
Using with a Thumbnail

### ISSUE THREAD

**Issue by Anahkiasen** [react-bootstrap/react-router-bootstrap#171]
I tried doing the following but then none of the children of `Thumbnail` show up:

```js
<LinkContainer to="/test">
    <Thumbnail src='foobar'>
        <Link to="test2">Something</Link>
    </Thumbnail>
</LinkContainer>
```

Is there a way to add a link on a thumbnail's thumbnail?

**Comment by jquense** [comment]
wrap the thumbnail in an anchor tag?

**Comment by Anahkiasen** [comment]
The `href` prop on `Thumbnail` is the anchor wrapping the image within the thumbnail, not the anchor on the thumbnail itself. Basically I want to set a link on the image, which react-bootstrap allows me to, but I can't make it a react-router link currently. Not sure if I'm clear

**Comment by Anahkiasen** [comment]
I want to add a react-router link on the image here:

![screen shot 2016-05-28 at 15 21 40](https://cloud.githubusercontent.com/assets/1321596/15627546/e5b7de26-24e7-11e6-876a-137f7150b02f.png)

But the thumbnail can still have children which are themselves button/links/whatever

**Comment by taion** [comment]
We just need to forward `onClick` in addition to `href` there I think.

**Comment by taion** [comment]
Please re-open this issue against R-B for passing `onClick` to the link in the thumbnail.
