### ISSUE TITLE
NavDropdown all MenuItem are selected

### ISSUE THREAD

**Issue by kevinludwig** [react-bootstrap/react-router-bootstrap#173]
Hi, 
I'm not sure if this is an issue or intended behavior. When I have a NavDropdown, like this:

```
<NavDropdown>
    <LinkContainer to='/some/path'><MenuItem>Menu1</MenuItem></LinkContainer>
    <LinkContainer to='/some/other/path'><MenuItem>Menu2</MenuItem></LinkContainer>
</NavDropdown>
```

It sets all the MenuItem to state active (so the whole submenu is the selected color. There is a workaround which is why I'm not sure if this is intended or not: I can do:

```
<NavDropdown>
    <LinkContainer onlyActiveOnIndex={true} to='/some/path'><MenuItem>Menu1</MenuItem></LinkContainer>
    <LinkContainer onlyActiveOnIndex={true} to='/some/other/path'><MenuItem>Menu2</MenuItem></LinkContainer>
</NavDropdown>
```

But I'm really not sure the intention of that particular property, and it seems kind of weird that a basic use case is broken unless I go into the LinkContainer code to look for an undocumented/under-documented property to fix my issue.

**Comment by taion** [comment]
The "active" status is computed from the LinkContainer. This is intentional. You probably have something like the first link linking to a parent route or something, e.g. one linking to `/a` and the other linking to `/a/b`.

**Comment by kevinludwig** [comment]
@talon
Maybe I wasn't clear.

What I'm saying is that the behavior of the `NavDropdown` behaves correctly (from a visual perspective) if the `LinkContainer` isn't present, and when I add `LinkContainer` the visual behavior changes (breaks). I'm pretty sure that the intention of `LinkContainer` is to make bootstrap links work with `react-router` without in any way changing the visual behavior of the bootstrap component. So I think there is a bug here.

**Comment by kevinludwig** [comment]
In particular when NavDropdown is in active state it does not mean all the child Menuitem are also in active state.

**Comment by taion** [comment]
The link container also overrides the item active state with the active state from the link.

**Comment by kevinludwig** [comment]
I'm not sure I understand. Are you saying you think the existing behavior is correct? That when I click to open a drop down, the whole thing, the whole submenu is blue (selected color)?  Because that's what happens, and it's not the way a drop down is supposed to behave.

**Comment by taion** [comment]
No – take a look at the visual test for Dropdown.

**Comment by kevinludwig** [comment]
You're missing a test case. It's broken.

https://github.com/react-bootstrap/react-router-bootstrap/pull/174/files

**Comment by taion** [comment]
Again, this is entirely a usage error on your end. If you start from the `MenuItemVisual` test case, you can verify that the following works:

```js
<Navbar>
  <Nav>
    <NavDropdown title="Dropdown">
      <LinkContainer to="/home">
        <MenuItem>Action</MenuItem>
      </LinkContainer>
      <LinkContainer to="/menu-item">
        <MenuItem>Active action</MenuItem>
      </LinkContainer>
      <LinkContainer to="/home">
        <MenuItem>Another action</MenuItem>
      </LinkContainer>
      <MenuItem divider />
      <LinkContainer to="/home">
        <MenuItem>Separated link</MenuItem>
      </LinkContainer>
    </NavDropdown>
  </Nav>
</Navbar>
```

**Comment by kevinludwig** [comment]
@talon. Ok I can accept that it's a usage error, can you explain how I've misused it though? What is the correct usage in my example? Because from my perspective I had a working NavDropdown and I added LinkContainer around it, as described in the docs, and the visual behavior changes.

**Comment by kevinludwig** [comment]
ok I see. It doesn't work if there are links pointing to '#'. Thats fine. I'll just point out that the behavior is different in this case (e.g. react-bootstrap works with '#' links) , and using '#' for a link is common when you're stubbing out a UI.

**Comment by chouclee** [comment]
I understand what taion means. However this is just weird compared to standard react-bootstrap.
We can do perfectly in react-bootstrap with:
``
<Navbar>
  <Nav>
   <NavItem href="/">Home<NavItem>
   <NavItem href="/user">Profile<NavItem>
  </Nav>
</Navbar>
``
Only one NavItem will be active each time.

However, when warpped with ``LinkContainer``, if user is on ``/user`` page, both NavItems will be active just like taion said above. In this case, how should we make react-router-bootstrap works like react-bootstrap? Personally I think that's what people cares. A simple wrapper, without interfering their original design.

**Comment by taion** [comment]
Use IndexLinkContainer. Refer to how React Router active semantics work.

**Comment by chouclee** [comment]
@taion Just found the solution.@151
Thank you.
