### ISSUE TITLE
LinkContainer triggers "unknown prop" warning in React.js 15.2

### ISSUE THREAD

**Issue by donpark** [react-bootstrap/react-router-bootstrap#176]
`LinkContainer` setting `active` prop in child anchor tag causes React.js 15.2 to complain.

    warning.js:44Warning: Unknown prop `active` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
        in a (created by AppView)
        in li (created by AppView)
        in ul (created by AppView)
        in nav (created by AppView)
        in div (created by AppView)
        in AppView (created by RouterContext)
        in RouterContext (created by Router)
        in Router

See [react-unknown-prop](https://fb.me/react-unknown-prop) mentioned in the warning for more details.

**Comment by taion** [comment]
There is no `LinkContainer` in that element stack you've posted.

**Comment by donpark** [comment]
That's because I had removed LinkContainer to remove the warning in my code then added active attribute to anchor tag to just trigger equivalent warning to file this issue with.

**Comment by taion** [comment]
I think you're misunderstanding what that warning means, and what the point of `<LinkContainer>` is.

`<LinkContainer>` is exactly intended to inject down `onClick`, `href`, and `active` props. It's the responsibility of the contained component (as is the case with React-Bootstrap components) to strip out the `active` prop and render the relevant active state.

**Comment by sercanov** [comment]
I have the same issue.

![ekran resmi 2016-08-16 11 28 33](https://cloud.githubusercontent.com/assets/10291644/17692833/9f24ad08-63a4-11e6-8f56-29e9e1ff505e.png)

Using  `"react-router-bootstrap": "^0.23.1", "react": "15.3.0"`

I could provide code sample if it needed but I think the issue is clear. Using Collapsable Navbar and LinkContainer inside them.

**Comment by fedevela** [comment]
@sercanov i was able to fix that by rolling back to a previous git version, then deleting my npm folders (i had an issue with react-bootstrap in npm .. it was not installed D: ), then doing npm install, then slowly adding one react component a time, (YOUR issue happened when i had some wrongly named attributes) and now my navbar works fine!!!

`  render() {
    return (
      <div>
          <Navbar>
            <Navbar.Header>
              <Navbar.Brand>
                <a href="/">
                    <img src="/Logo.png"
                        width="200px"/>
                </a>
              </Navbar.Brand>
              <Navbar.Toggle />
            </Navbar.Header>
            <Navbar.Collapse>
              <Nav>
                
                <LinkContainer to="/admin">
                    <NavItem>
                      Admin
                    </NavItem>
                  </LinkContainer>
                  
`

**Comment by sercanov** [comment]
@fedevela thanks for the info but I don't think it's such an issue to do all these things :D 

As @taion mentioned, active prop is required to manage state and styling of the current navigation but i think there should be a workaround for everyone.

**Comment by jquense** [comment]
the workaround is to upgrade to a newer version of react-bootstrap. The problem here is not LinkContainer it's NavItem

**Comment by dreyks** [comment]
There is no newer version, I'm at `0.30.3`

```jsx
<Nav>
  <IndexLinkContainer to="/"><NavItem>Home</NavItem></IndexLinkContainer>
  <LinkContainer to="/about"><NavItem>About</NavItem></LinkContainer>
</Nav>
```

still getting this, thou it does not affect anything, current route button is still being highlighted

**Comment by jquense** [comment]
You aren't supposed to use  `LinkContainer` with a plain dom element (`<a>`) This component will never stop injecting `active` to it's children as that is the entire point of it, you to you to make sure the child does not pass through the `active` prop

**Comment by dreyks** [comment]
Ok, I get it, then this is an issue with `NavItem`? _It_ has to prevent `active` to be passed through? Otherwise what is the correct usage of the `LinkContainer` <=> `NavItem` bundle?

**Comment by jquense** [comment]
You don't have a NavItem the problem is here:
```
in a (created by Unknown)
in LinkContainer (created by IndexLinkContainer)
```

**Comment by dreyks** [comment]
That is really strange, look at my JSX markup one post above.

I fell that is some stupid mistake of mine, but I can't really catch it

**Comment by jquense** [comment]
the error is not coming from that markup it's coming from your `NavbarBrand` please read your stack trace

**Comment by dreyks** [comment]
Daaamn, @jquense thanks a lot. I new that was something obvious.

**Comment by godmar** [comment]
FWIW, happens with Pager.Item in react-bootstrap@0.30.5 as well.

**Comment by AndrewRevinsky** [comment]
So what about NavbarBrand? What is the solution?

**Comment by discordianfish** [comment]
@AndrewRevinsky Was wondering the same.. I think I get the issue, but then it appears to me like there is a bug in NavbarBrand which doesn't remove the 'active' prop. But before we open another issue, maybe @taion or @jquense can confirm?

**Comment by nialloc9** [comment]
I had the same issue and was able to fix it by changing from <NavItem><LinkContainer></LinkContainer></NavItem> to <LinkContainer><NavItem></NavItem></LinkContainer>. When LinkContainer was wrapped with NavItem it gave me this error but changing it to wrap NavItem with LinkContainer fixed the issue for me.

**Comment by discordianfish** [comment]
Well, I have `<LinkContainer to="/"><Navbar.Brand>foo</Navbar.Brand></LinkContainer>` and still get this error. I use LinkContainer with NavItem and it works fine though.

**Comment by gabrielfgularte** [comment]
Same problem here. @dreyks how did you fixed?

**Comment by dreyks** [comment]
Don't remember exactly but i think i just removed the link from my NavbarBrand

**Comment by tulbox** [comment]
Also occurs with Navbar.Link (used in order to link to an external URL). I've worked around it instead by wiring up a NavItem to an onClick event that redirects. Are there any other suggestions?

 ```
      <Navbar.Collapse>
        <Nav>
          <LinkContainer to={{ pathname: '/listings'}}>
            <NavItem eventKey={1}>Sample</NavItem>
          </LinkContainer>
          <li>
           <Navbar.Link href="https://www.google.com" target="_blank">Leads to warnings</Navbar.Link>
          </li>
          <NavItem eventKey={6} onClick={this.handleExternalUrlRedirectClick}>Workaround</NavItem>
        </Nav>
        <Nav pullRight>
          <NavItem eventKey={8} onClick={this.handleClick}>Logout</NavItem>
        </Nav>
      </Navbar.Collapse>
```

**Comment by Sburke0708** [comment]
I'm still getting the issue. ```Warning: Failed context type: The context `router.history` is marked as required in `LinkContainer`, but its value is `undefined`.```

Any suggestions?

**Comment by Sburke0708** [comment]
Rolling back to `0.20.1` worked for me.
