### ISSUE TITLE
`NavItem` and `MenuItem` could be taken in charge as well?

### ISSUE THREAD

**Issue by zeachco** [react-bootstrap/react-router-bootstrap#178]
These two bootstrap components creates `a` tags as well

**Comment by taion** [comment]
What?

**Comment by zeachco** [comment]
Sorry for the lack of context

as this librairy make the link between _react-router_ and _react-bootstrap_ I thought it could be usefull to support the `Link` (from _react-router_) behaviour into `NavItem` and `MenuItem` (from _react-bootstrap_) as well

**Comment by zeachco** [comment]
an example ignoring _react-bootstrap_ being 
```

import {Link} from 'react-router';
// ...
      <li role="presentation">
        <Link to="/path">Somewhere...</Link>
      </li>
```
The issue with this one is that it does not handle closing dropdown option on certain components as we are not using the _react-bootstrap_ component

or 

```
import {MenuItem} from 'react-bootstrap';
// ...
<MenuItem><Link to="...">Another action</Link></MenuItem>
```
The issue with this one is that it create two nested `<a>` tags

**Comment by taion** [comment]
You're supposed to wrap `MenuItem` or `NavItem` in the provided `LinkContainer`.

**Comment by zeachco** [comment]
Makes more sense to me now, thanks, sorry for openning this issue in the first place
