### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [react-bootstrap/react-router-bootstrap#181]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I don't know which files should be added.
By the way, I use the npm package.
I saw there are some files in npm but not in github repo like ```ReactRouterBootstrap.js```.

Could you help me? 
Thanks!
https://github.com/cdnjs/cdnjs/issues/8816

**Comment by taion** [comment]
The distributed files are not checked in, because they're build artifacts. You most likely want the `ReactRouterBootstrap.*` files from the npm package.
