### ISSUE TITLE
Upgraded to React 15.3.1 now getting error invalid prop 'active' in span tag

### ISSUE THREAD

**Issue by atalebagha** [react-bootstrap/react-router-bootstrap#182]
Getting the following error after upgrading to React 15.3.1.  React-Router-Bootstrap updated to latest version as well.

<img width="568" alt="screen shot 2016-09-05 at 8 45 15 am" src="https://cloud.githubusercontent.com/assets/9886105/18262043/d05428c2-73b2-11e6-9ff4-53fc1611684a.png">

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-router-bootstrap/issues/176
