### ISSUE TITLE
MenuItem inside Dropdown no active class

### ISSUE THREAD

**Issue by mewben** [react-bootstrap/react-router-bootstrap#184]
I have this jsx:
```jsx
<NavDropdown eventKey={2} title="User Management" id="managesub">
	<LinkContainer to="/roles">
		<MenuItem eventKey={2.1}>Roles</MenuItem>
	</LinkContainer>
	<LinkContainer to="/users">
		<MenuItem eventKey={2.2}>Users</MenuItem>
	</LinkContainer>
</NavDropdown>
```

If I go to any of those routes, I noticed there's no active class. I did a bit tinkering around the `LinkContainer.js` code and commented some lines like this:

```js
// Ignore if rendered outside Router context; simplifies unit testing.
if (router) {
	props.href = router.createHref(to);

	// if (props.active == null) {
		props.active = router.isActive(to, onlyActiveOnIndex);
	// }
}
```

And it worked perfectly.

---

I'm using: 
react: 15.3.1
react-router: 2.8.1
react-bootstrap: 0.30.3
react-router-bootstrap: 0.23.1

---

**Comment by taion** [comment]
We already have an issue for this on React-Bootstrap.
