### ISSUE TITLE
Would be great to see LICENSE file and license in front page.

### ISSUE THREAD

**Issue by VyvIT** [react-bootstrap/react-router-bootstrap#187]
What license this code is under?

**Comment by taion** [comment]
Apache: https://github.com/react-bootstrap/react-router-bootstrap/blob/master/package.json#L30

**Comment by taion** [comment]
I wish we could relicense this to MIT or something just for consistency with everything else, though.

**Comment by VyvIT** [comment]
May I ask, what is restricting it to relicense as MIT?

**Comment by taion** [comment]
It was initially licensed as Apache, and none of us have time to track down everyone who contributed to relicense to MIT.

**Comment by mtscout6** [comment]
As the original author I have no problem with changing the license. I think we would need sign-off from all contributors to date though. I may be wrong about that, I'm not a lawyer.

**Comment by taion** [comment]
Is there any drawback in practice to using Apache? I don't think the license should really exclude anything.

**Comment by mtscout6** [comment]
Not that I'm aware of, just my two sense that I don't care if it's MIT or Apache. If it's causing issues by being Apache then we can change it.
