### ISSUE TITLE
Docs should mention requirement of withRouter decorator

### ISSUE THREAD

**Issue by flof** [react-bootstrap/react-router-bootstrap#198]
I had some problems with the Navbar showing the current active NavItem highlighted. I found that the LinkContainer component expects **router** in the context. So I tried to decorate my component with the `withRouter` decorator function from the **react-router** package. And then it worked. 

It should be mentioned in the docs that every component that uses `LinkContainer` or `IndexLinkContainer` must be decorated with `withRouter`. 

Or am I missing something here?

**Comment by jquense** [comment]
you have some other issue. `withRouter` adds router to `props` _from_ context, It doesn't make sure that router is on context. As long as the LinkContainers are rendered below the Router component it should work fine
