### ISSUE TITLE
Provide a more agnostic NavItem in react-bootstrap

### ISSUE THREAD

**Issue by gnapse** [react-bootstrap/react-router-bootstrap#204]
Isn't it simpler to provide a more agnostic `NavItem` in `react-bootstrap` that renders just the `<li>` element, and let the code using it define the content (children elements) within that tag?

```javascript
const NavItem = ({ className, active, disabled, style, children }) => {
  const classNames = classnames(className, { active, disabled });
  return (
    <li role="presentation" style={style} className={classNames}>
      {children}
    </li>
  )
}
```

Then use it to provide nav-items that render a `react-router` `<Link to="...">`:

```javascript
const AppNav = () => (
  <Navbar inverse fixedTop>
    <Navbar.Header> ... </Navbar.Header>
    <Nav>
      <NavItem>
        <Link to="/about">About</Link>
      </NavItem>
    </Nav>
  </Navbar>
)
```

FWIW, that's what I did in my own app. Because I find it unappealing to have to wrap my `NavItem`s inside this `LinkContainer` just to achieve that.

**Comment by taion** [comment]
it really only makes that one case useful and doesn't help much else, plus you need to jump through hoops to get router active state. that's why `<LinkContainer>` is the recommended solution.
