### ISSUE TITLE
Version 0.24 in npm? 

### ISSUE THREAD

**Issue by olmobrutall** [react-bootstrap/react-router-bootstrap#205]
I'm in the process of updating to react-router 4 and looks like this library is ready but not published in npm. Any reason? 

BTW: I have a PR in definitely typed to update the typescript type definitions to 0.24

**Comment by v12** [comment]
It should be published very soon as I asked publishers to do this.

And thank you for PR to DefinitelyTyped, however, I think you shouldn't change `lib` to `src` in paths. `lib` gets created during release and `src` is excluded from published version of package.

**Comment by olmobrutall** [comment]
Fixed https://github.com/DefinitelyTyped/DefinitelyTyped/pull/1591

I've tried to `npm install` version 0.24 directly from github with no results. Is there anyway to do it?

**Comment by v12** [comment]
You can navigate to `react-router-bootstrap` folder and run `yarn run build` to build the project

**Comment by olmobrutall** [comment]
Mmm, without a change in project.json it's too much trouble for other devs. I'll wait till is published then

**Comment by taion** [comment]
released v0.24.1
