### ISSUE TITLE
react v15.5 w/o forcing react-router v4 upgrade?

### ISSUE THREAD

**Issue by travi** [react-bootstrap/react-router-bootstrap#211]
any chance that the react v15.5 changes will be backported to a version that doesn't require an upgrade to router v4? 

i'm trying to upgrade a project to react v15.5 that is not able to upgraded to router v4 yet and this is my current (hopefully last) sticking point. the react-overlays bump in react-bootstrap got me to this point, so i'm hoping this won't prevent finishing the react upgrade.

thanks for any help you're able to provide here.

**Comment by taion** [comment]
they already were in 0.23.2...

**Comment by travi** [comment]
ah, great news. thanks! 

since that version isn't in [the changelog](https://github.com/react-bootstrap/react-router-bootstrap/blob/master/CHANGELOG.md#v0240), i didn't realize that was the case
