### ISSUE TITLE
Will something like NavLinkContainer be implemented?

### ISSUE THREAD

**Issue by Ogglas** [react-bootstrap/react-router-bootstrap#212]
Today I needed to change the active elements CSS in a Nav. NavLink has both activeStyle and activeClassName which would be really good here. Are there any thoughts on implementing a NavLinkContainer?

https://reacttraining.com/react-router/web/api/NavLink

http://stackoverflow.com/questions/44019274/react-tsx-with-react-bootstrap-inline-css-for-active-navitem

**Comment by v12** [comment]
`LinkContainer` is effectively react-router's `NavLink` but tailored for react-bootstrap.

You can use both `activeStyle` and `activeClassName` with `LinkContainer`. See [lines 30 & 32](https://github.com/react-bootstrap/react-router-bootstrap/blob/8e0fa33fe49004419b4f9c3c417fb58d16bb5182/src/LinkContainer.js#L30).

**Comment by Ogglas** [comment]
Ah I'm using TypeScript and it seems Types was not updated. Created a pull request.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16600
