### ISSUE TITLE
Not set class "active" to NavBar

### ISSUE THREAD

**Issue by perevezencev** [react-bootstrap/react-router-bootstrap#214]
Example is [here](https://codesandbox.io/s/G66Jx1xA3). When route is `./sampleHotelName/dashboard` or `./sampleHotelName/pricing` in `NavBar `do not set up `class="active"` for `NavItem`. What am I doing wrong?

**Comment by v12** [comment]
Working with relative paths in React Router was always tricky. It has nothing to do with react-router-bootstrap as internally we use react-router's route matching.

To narrow it down, [matchPath](https://reacttraining.com/react-router/web/api/matchPath) is the function that causes your example to fail.

As a fix I'd suggest explicitly setting path in your links, i.e. using `baseUrl`. See following [example](https://codesandbox.io/s/68PPBq6LR).

However, I'd question your current architecture of application and rework it to be more "modularised". As in your `WorkSpace` component you're matching against same base, however, in my opinion, you should be matching your `./dashboard`, `./pricing` down in the Workspace layout. Or, even better, move layout up to Workspace container, so `Header` component is matching against `/:hotelName` and not `/:hotelName/:whatever` - there will be no need for additional `baseUrl` to be passed down through all components and you'll be using `match` directly.

**Comment by perevezencev** [comment]
LIke [this ](https://codesandbox.io/s/p3QnyDRN)?
