### ISSUE TITLE
TypeError: Cannot read property 'createHref' of undefined LinkContainer

### ISSUE THREAD

**Issue by MHerszak** [react-bootstrap/react-router-bootstrap#216]
I just ran into this problem. It only started to appear today. No issues before. I am using this.context.router in my project as well but it never threw an issue before. Any ideas?
![screen shot 2017-06-20 at 13 59 42](https://user-images.githubusercontent.com/4604432/27353444-43694ca2-55c1-11e7-811a-e5246ea7585c.png)

**Comment by v12** [comment]
> I am using this.context.router in my project

Seems that something has messed up with the context up in the tree. What changes have you done before this issue appeared?

**Comment by MHerszak** [comment]
So I had this issue while using package-lock. I am not sure why npm would mess this up but not using package-lock was one solution.

**Comment by manonthemoon42** [comment]
@MHerszak , I am facing the same issue. 
Tried to delete package-lock but that didn't fix it. 

Any other thing that I should do?
