### ISSUE TITLE
ActiveClass Matching on root path Problem

### ISSUE THREAD

**Issue by zhenyulin** [react-bootstrap/react-router-bootstrap#217]
I'm having a route of `/home`, and being redirected to '/' in react-router; If I do `to={'/'}`, then the root link item will be active all the time; If I do `to={'/home'}`, then under `/` path, the activeClass wouldn't be activated.

Is there an elegant way to solve this?

**Comment by v12** [comment]
If you want `/home` link to be highlighted when you're at `/` - I'm afraid there is no straightforward way of getting round this.

If you want `/` link to be highlighted when you're at `/` - use `exact` option. If it's set to `true`, your link will be active only when route exactly matches (`===`) link URL

**Comment by zhenyulin** [comment]
@v12 , I found a way to redirect '/' to '/home' and fixed the highlight issue.
