### ISSUE TITLE
Active Property Isn't Set Unless Page Is Refreshed

### ISSUE THREAD

**Issue by firrae** [react-bootstrap/react-router-bootstrap#220]
Hey there,

Currently my code looks like this:

```javascript
<NavDropdown title={this.getUserName()} eventKey={2} id="profile-dropdown">
     <LinkContainer to="/profile" exact activeClassName="active-menu-item">
          <MenuItem eventKey={2.1}>
               View/Edit Profile
          </MenuItem>
     </LinkContainer>
     <LinkContainer to="/profile/settings" exact activeClassName="active-menu-item">
          <MenuItem eventKey={2.2}>
               Settings
          </MenuItem>
     </LinkContainer>
     <MenuItem divider />
     <MenuItem eventKey={2.99} onClick={this.userLogout}>
          Logout
     </MenuItem>
</NavDropdown>
```

Currently when I navigate to either the Settings or View/Edit Profile pages neither of the links highlight, but, if I'm on one of those pages, when I refresh it gets selected and never gets deselected after navigating away meaning another page refresh is needed.

Is this something I'm doing incorrectly? If so please let me know.

Thanks,

Steve

**Comment by v12** [comment]
Hi Steve, I'm afraid but I can't reproduce the issue with your code snippet. Could you please create an example somewhere, which replicates what you described (you may use [codepen.io](https://codepen.io/) for instance)?

What I assume is that something up in the tree blocks re-render (i.e., `shouldComponentUpdate` returns `false`). This is quite common problem that people hit when using Redux.

**Comment by firrae** [comment]
I can try to, I'm mildly wondering if it's an issue with the framework it's all running in which is Meteor. There is nothing I could think to cause an issue, but it's the only thing that isn't standard to your examples. I'll see if I can do something up to recreate it.

**Comment by firrae** [comment]
So it seems my issue is identical to this one: https://github.com/react-bootstrap/react-router-bootstrap/issues/152#issuecomment-203688394 except I'm not using React-Redux, I'm just using the Meteor react-meteor-data package. Maybe that I guess is interfering in the same way?

**Comment by firrae** [comment]
I think this might be it, looks like here https://github.com/meteor/react-packages/blob/devel/packages/react-meteor-data/ReactMeteorData.jsx#L167 they default the connect to being "pure" with the solution to #152 being to set pure to false.

**Comment by firrae** [comment]
This comment pointed me to the correct answer to my issue: https://github.com/meteor/react-packages/issues/222#issuecomment-303810160. It was indeed the fact it was looking to create a pure component. Sorry for the spam, but hopefully if someone else runs into this it can help them.

**Comment by v12** [comment]
@firrae Glad you managed to resolve this. And thank you for letting us know what caused this issue in your case, much appreciated!
