### ISSUE TITLE
How to import? require?

### ISSUE THREAD

**Issue by wzup** [react-bootstrap/react-router-bootstrap#221]
How to import, require the package?

**Comment by v12** [comment]
Either `yarn add react-router-bootstrap` or `npm install react-router-bootstrap`

You can use in your code then as follows.

In case you use [ES2015 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import):
```js
import { LinkContainer } from 'react-router-bootstrap'
```
Or with [CommonJS](http://wiki.commonjs.org/wiki/Modules/1.1.1):
```js
const { LinkContainer } = require('react-router-bootstrap')
```
