### ISSUE TITLE
Doesn't work with ToggleButtonGroup

### ISSUE THREAD

**Issue by bobics** [react-bootstrap/react-router-bootstrap#222]
When I wrap `ToggleButton` with `LinkContainer`, it ignores the `defaultValue` as well as button clicks.

```jsx
<ToggleButtonGroup type={'radio'}
                   name={'options'}
                   className={'btn-group-sm'}
                   defaultValue={
                     this.props.myButtonVal || "foo"
                   }>
  <LinkContainer to="/foo">
    <ToggleButton value={"foo"}>foo</ToggleButton>
  </LinkContainer>
  <LinkContainer to="/bar">
    <ToggleButton value={"bar"}>bar</ToggleButton>
  </LinkContainer>
</ToggleButtonGroup>
```

It's unclear how to workaround this, thanks.

**Comment by taion** [comment]
This use case doesn't really make sense. The toggle button groups are supposed to represent form components like checkboxes or radio groups. Just use a normal button group instead.

**Comment by bobics** [comment]
Thanks for the insanely fast reply.
