### ISSUE TITLE
LinkContainer isActive expects a function, not boolean

### ISSUE THREAD

**Issue by Bandit** [react-bootstrap/react-router-bootstrap#223]
This doesn't work when you try to implement the following approach for making custom matches, as described in `react-router`:

https://github.com/ReactTraining/react-router/pull/4499#issuecomment-284950421

Can we patch it so it can be a function or a boolean so I can implement this custom matching on my non-standard menu items:

```jsx
const accountSelected = (accountId) => {
  return (accountId === Meteor.user().selectedAccountId);
};

[...]

<LinkContainer
        key={account._id}
        to="#"
        isActive={accountSelected(account._id)}
      >
```

=>

```
Warning: Failed prop type: Invalid prop `isActive` of type `boolean` supplied to `LinkContainer`, expected `function`. in LinkContainer
```

**Comment by v12** [comment]
It works the same way it's described in the link you posted.

If you want to make your code work, either use `isActive={() =>accountSelected(account._id) }` or rewrite `accountSelected` function to:
```js
const accountSelected = (accountId) => {
  return () => (accountId === Meteor.user().selectedAccountId);
};
```
