### ISSUE TITLE
install failing

### ISSUE THREAD

**Issue by rsmolkin** [react-bootstrap/react-router-bootstrap#227]
I tried to run it as Administrator on Windows 7.  Get this error:

PS C:\myapp> npm i -save react-router-bootstrap
npm ERR! path C:\myapp\node_modules\fsevents\node_modules\getpass\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\myapp\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\myapp\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\myapp\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

**Comment by taion** [comment]
This seems like a local permission misconfig. It doesn't look related to this library.
