### ISSUE TITLE
Warning: Failed context type: The context `router.history` is marked as required in `LinkContainer`, but its value is `undefined`.

### ISSUE THREAD

**Issue by supritshah1289** [react-bootstrap/react-router-bootstrap#230]
@taion 

I'm trying to connect react-bootstrap NavItem link with pages Link I have. I tried wrapping LinkContainer but I got few errors. I have successfullly connected pages link using React router but I was not able to connect it using react-bootstrap and react-router-bootstrap. Please help.
[package.json](https://github.com/supritshah1289/sellyourskills/blob/master/package.json)
[working file](https://github.com/supritshah1289/sellyourskills/blob/master/src/components/common/Header.js)

**Comment by taion** [comment]
Most likely you have the wrong version installed.

**Comment by supritshah1289** [comment]
@taion  what is the correct version?

**Comment by supritshah1289** [comment]
To anyone looking at this post. If you're having the same issue while connecting react-bootstrap with react-router-bootstrap. Please use react-router-bootstrap version 3. 
[github link](https://github.com/react-bootstrap/react-router-bootstrap)

1.  Remove react-router-bootstrap from your package.json
2. Delete node_modules
3. add "react-router-bootstrap": "^0.23.3",
4. npm install

**Comment by v12** [comment]
@supritshah1289 your solution is misleading. Version 0.23.x is for React Router v3, whereas latest version (0.24.4 as of now) should be used with React Router v4.

**Comment by supritshah1289** [comment]
@v12  Oh I'm using 
"react-router": "2.5.2",
"react-dom": "15.3.0",
"react": "15.3.0",
"react-router-bootstrap": "^0.23.3"

This combination worked for me.

**Comment by v12** [comment]
@supritshah1289 correct, you now have appropriate version of react-router-bootstrap that works with your version react-router. In future, refer to [this section](https://github.com/react-bootstrap/react-router-bootstrap#installation) where it's mentioned what release tag you should use.

**Comment by davisford** [comment]
@v12 I'm seeing this same error with this configuration:

```
+-- react@16.2.0
+-- react-bootstrap@0.31.5
+-- react-dom@16.2.0
+-- react-router-bootstrap@0.24.4
+-- react-router-dom@4.2.2
```

That config should be ok, right?
