### ISSUE TITLE
Can't Resolve react-router-dom

### ISSUE THREAD

**Issue by wuno** [react-bootstrap/react-router-bootstrap#231]
I am using react-bootstrap and react-router in my React application. I installed react-router-bootstrap so I could use Nav.Item and LinkContainer for my routes. Originally when I set it all up I kept getting this error. 

> ./node_modules/react-router-bootstrap/lib/LinkContainer.js
> Module not found: Can't resolve 'react-router-dom' in '/Users/wuno/Dropbox/Hack/Devops/react/riverwalk-credit-web/node_modules/react-router-bootstrap/lib'

I left the computer alone for a bit came back and started up the server again, `npm start` and it worked fine. At this point I decided to do some refactoring which broke it again giving me the same error as mentioned above. At this point I set everything back to the last working state and the error was still there. 

I checked the node_modules directory and I do not see a` react-router-dom`  inside of the lib folder or where it is even referencing this. But when I check the repo on git there does seem to be a reference for the library inside of `LinkContainer`. 

I am thinking this must be a bug but this is my first time using any of these tools. All my experience is with react-native. 

index.js

```
import { Router, Route } from 'react-router';
<Router>
      <div>
        <Navigation />
        <Route exact path="/" component={HomeContainer} />
      </div>
    </Router>
```

Navigation

```
import { LinkContainer } from 'react-router-bootstrap';
  <LinkContainer to="/">
     <NavItem>Home</NavItem>
   </LinkContainer>
```

Error 

> ./node_modules/react-router-bootstrap/lib/LinkContainer.js
> Module not found: Can't resolve 'react-router-dom' in '/Users/wuno/Dropbox/Hack/Devops/react/riverwalk-credit-web/node_modules/react-router-bootstrap/lib'

**Comment by jquense** [comment]
Have you tried installing react-router-dom

**Comment by wuno** [comment]
I did try installing it. But that did not help. Also it worked for a a few minutes before I refactored without react-router-dom. So I am not sure why that would make a difference. 

Is react-router-dom a dependency? It does not say that in the readme.md. If it is how would go about importing it to make it work with react-router-bootstrap?

**Comment by wuno** [comment]
Actually I just now got it to work. You were right that is what it needed but the import is like this, 
`
import { BrowserRouter as Router, Route } from 'react-router-dom';`

Thanks for your help. Is there docs anywhere explaining this?

**Comment by v12** [comment]
@wuno glad that you managed to resolve the issue you had.

Have a look at react-router's [installation guide](https://github.com/ReactTraining/react-router/tree/0e6f1a37a2540595e776858c52e924cc74590d6b/packages/react-router#installation), which has a note about packages that should be used for development. You'd never reference `react-router` directly in your web application because `react-router-dom` is supposed to be used instead.

**Comment by princecharming519** [comment]
Hello, Web experts.
I just met a compile error like wuno.

I imported everything as the following. 
import React, { Component } from 'react';
import { BrowserRouter as Router, Route } from 'react-router-dom';

But still, error didn't resolve.
Failed to compile.

./src/App.js
Module not found: Can't resolve 'react-router-dom' in '/Volumes/Source....../src'
I don't know why it happened.

Please help me.

**Comment by werneckbh** [comment]
@princecharming519 , I assume you're using docker. If so, drop your images and recreate them. This solved my problem.

**Comment by babusng** [comment]
Hi please help to resolve my compile error.
while import react-router-dom getting error 
![screenshot from 2018-11-08 15-34-48](https://user-images.githubusercontent.com/43462487/48327669-edc50e80-e665-11e8-9f9c-7178d98d5f6e.png)
Cannot find module 'react-router-dom'

**Comment by v12** [comment]
@babusng with the level of details you provided it's impossible to help you to resolve the issue.

My suggestion is to run `npm install react-router-dom` (or `yarn add react-router-dom` if you're using Yarn). Then check that the import is referencing package name, not path (i.e., it should be `require('react-router-dom')`, not `require('./react-router-dom')`)

**Comment by webcodestar** [comment]
Did you try to restart dev server?

**Comment by SommieDivy** [comment]
I got the same kind of error. Please how can I fix this as I am new to react?
![error](https://user-images.githubusercontent.com/47015109/51867257-2e980e00-239f-11e9-84e5-3df354d3c8f7.PNG)

**Comment by SommieDivy** [comment]
wow! thanks man. its been resolved

**Comment by davidkhanpk** [comment]
just install react-router-dom with --save and you are good to go

**Comment by moyuanhuang** [comment]
I got the same error when using create-react-app with Ruby on Rails. Turned out that after initialization, all the packages are installed under `/client` folder. I need to `cd client` before running `yarn add react-dom react-router-dom` so that the server can correctly find the packages.

**Comment by ggbeppe** [comment]
> @princecharming519 , I assume you're using docker. If so, drop your images and recreate them. This solved my problem.

Wasted so much time with this 🤦‍♂️

**Comment by wikak** [comment]
> just install react-router-dom with --save and you are good to go

this Work for me !

**Comment by lopezdp** [comment]
I am dealing with this same issue on two new projects I have just started and I have it configured the way I have it on another in production and for some reason I can't seem to find the bug here.

Here are my dependencies in my `package.json`:

```
"dependencies": {
    "react": "^16.8.6",
    "react-bootstrap": "^0.32.4",
    "react-dom": "^16.8.6",
    "react-router-dom": "^4.3.1",
    "react-scripts": "3.0.1"
```

I have an `index.js` file where I am wrapping my `<App />` component inside of the `<Router />` component that I am importing with `BrowserRouter` as specified from `react-router-dom`.

Here are the contents of my `index.js` file:

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import { BrowserRouter as Router } from 'react-router-dom';

ReactDOM.render(
  <Router>
    <App />
  </Router>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

From there my `<App />` component implements a custom `<Routes />` component that uses `Route` and `Switch` from `react-router-dom` to handle my app's routing needs.

Here are the contents of my `<App />` component:


import React, { Component } from "react";
import { Link } from "react-router-dom";
import { Navbar } from "react-bootstrap";
import Routes from "./Routes.js";
import "./App.css";

class App extends Component {
  render() {
    return (
      <div className="App container">
        <Navbar fluid collapsOnSelect>
          ...... misc navbar code
        </Navbar>
        <Routes />
      </div>
      );
  }
}

export default App;
```

This is what my `Routes.js` file looks like and how it uses the `Route` and `Switch` from `react-router-dom`:

```
import React from "react";
import { Route, Switch } from "react-router-dom";
import Home from "./containers/Home";

export default () => <Switch>
                       <Route path="/" exact component={ Home } />
                     </Switch>;
```

Here is the `{ Home }` component that I am trying to serve up locally:

```
import React, { Component } from "react";
import "./Home.css";

export default class Home extends Component {
  render() {
    return (
      <div className="Home">
        <div className="LandingPage">
          ... random html code
        </div>
      </div>
      );
  }
}
``` 

And finally here is the error:

<img width="1063" alt="Screen Shot 2019-05-29 at 1 45 08 PM" src="https://user-images.githubusercontent.com/5707191/58578972-0f5ba100-8218-11e9-94e9-6a547f0e4b1e.png">

What do you think could be the problem here??? Thanks !

**Comment by v12** [comment]
@lopezdp this has nothing to do with `react-router-bootstrap`. Please check the structure of your project and paths of the files you're referencing in your imports.

**Comment by lopezdp** [comment]
> @lopezdp this has nothing to do with `react-router-bootstrap`. Please check the structure of your project and paths of the files you're referencing in your imports.

You're right! I totally had it in the wrong directory! Sorry about the inconvenience and thanks for taking a look!

**Comment by fabellonnoe** [comment]
`npm install --save react-router-dom` this will do. thank me later

**Comment by kengreg** [comment]
> 
> 
> @princecharming519 , I assume you're using docker. If so, drop your images and recreate them. This solved my problem.

Thanks ! 4 hours spending looking for a fix...and it was only this...god....

**Comment by carlitosz** [comment]
I had the same issue suddenly after uninstalling some packages.

This worked for me: `rm -rf /node_modules` and then `npm install`

**Comment by HanJerry141592** [comment]
Update react-router-dom with new version 5.0.0.
It is working after I updated with new version.

**Comment by aidanolima** [comment]
ERROR: Module not found: Can't resolve './pages/Register' in 'C:\www\semanaomnistack11\aulas\frontend\src'

import React, { Component } from "react";
import { BrowserRouter, Route, Switch } from 'react-router-dom';

import Logon from './pages/Logon';
import Register from './pages/Register';

export default function Routes(){
    return (
        <BrowserRouter>
          <Switch>
          <Route path='/' exact component={Logon} />
          <Route path='/register'component={Register} />
          </Switch>--    
        </BrowserRouter>

    );
}

**Comment by premrex** [comment]
![image](https://user-images.githubusercontent.com/32057061/79685401-379c2600-8256-11ea-8ff3-835129d3b4eb.png)

try this way too , it will work

**Comment by suraj27499** [comment]
> I got the same error when using create-react-app with Ruby on Rails. Turned out that after initialization, all the packages are installed under `/client` folder. I need to `cd client` before running `yarn add react-dom react-router-dom` so that the server can correctly find the packages.

In my case i used "yarn add  react-router-dom" yarn and it worked perfectly but "npm i react-router-dom --save " was not working.

**Comment by vinodkv007** [comment]
> Have you tried installing react-router-dom

This solved the issue for me.
I installed the module in client directory using ``npm i react-router-dom`` command, and the issue got fixed.

**Comment by srikanthvaijapur** [comment]
> Hello, Web experts.
> I just met a compile error like wuno.
> 
> I imported everything as the following.
> import React, { Component } from 'react';
> import { BrowserRouter as Router, Route } from 'react-router-dom';
> 
> But still, error didn't resolve.
> Failed to compile.
> 
> ./src/App.js
> Module not found: Can't resolve 'react-router-dom' in '/Volumes/Source....../src'
> I don't know why it happened.
> 
> Please help me.

npm i react-router-dom'
it worked for me

**Comment by Jhlan** [comment]
For this problem "Module not found: Can't resolve 'react-router-dom' in"
I found the following solving

// using ES6 modules
import { BrowserRouter, Route, Link } from "react-router-dom";

 if it is nor working so you have to use the following that I used
// using CommonJS modules
const BrowserRouter = require("react-router-dom").BrowserRouter;
const Route = require("react-router-dom").Route;
const Link = require("react-router-dom").Link;

**Comment by FlavioAandres** [comment]
In my case, i was installing the library in the backend folder, so... layer 8 error :)

**Comment by mubbarikali** [comment]
> just install react-router-dom with --save and you are good to go

Thank you so much.. You helped me a lot....

**Comment by Bhavnoor-Singh98** [comment]
> `npm install react-router-dom` or
> `yarn add react-router-dom`
> and restart the server
Thanks a lot. It helped me and don't forget to restart the server.

**Comment by moleseee** [comment]
For me a react-router-dom dependency was missing. I ran 'npm install babel --save' and it fixed it.

**Comment by execptionerror** [comment]
[[Solved] Failed to compile ./src/components/App/App.js Module not found: Can’t resolve ‘react-router-dom’](https://exerror.com/failed-to-compile-src-components-app-app-js-module-not-found-cant-resolve-react-router-dom/)
