### ISSUE TITLE
Hash-link navigation using HTML5 history

### ISSUE THREAD

**Issue by robpaveza** [react-bootstrap/react-router-bootstrap#233]
Hey - great lib, very helpful!  However, I have an app that I'm migrating that uses hash links.  It turns out that there's another library that scrolls hash-navigation into view when using react-router: 

https://github.com/rafrex/react-router-hash-link

but since this adapter doesn't compose the same way (I have to put `LinkContainer` outside of `MenuItem`), I can't use `HashLink`.

Would you consider supporting something like a `HashLinkContainer` or `scrollHash` prop?

**Comment by v12** [comment]
Isn't [custom <Link>](https://github.com/rafrex/react-router-hash-link/tree/fc52647868f8baab78faccab24eff54b2966a57e#custom-link) is what you need?

I'll close this issue as we're unlikely to implement anything related to scrolling to keep the implementation in-line with `react-router`'s <NavLink>.

However, if you have any suggestions that'll result in unintrusive change, feel free to propose it 👍
