### ISSUE TITLE
Match query string

### ISSUE THREAD

**Issue by PawelMorawian** [react-bootstrap/react-router-bootstrap#235]
When I have 2 URLs like this :

`<LinkContainer to={{pathname: this.props.match.url, search: 'param=1'}}>`
`<LinkContainer to={{pathname: this.props.match.url, search: 'param=2'}}>`

Both of the NaItem are active. How to prevent this from happening ?

**Comment by v12** [comment]
Even though it may be too late but behind the scenes, `react-router-bootstrap` uses [`<Route>`](https://reacttraining.com/react-router/web/api/Route) component to match your current URL. We also accept objects as an input but only `pathname` property is used (in a similar way `react-router` works with `<NavLink>`).

If you need to match querystring as part of your route, I'd suggest using regular expression - see react-router's <Route> documentation for `path`, which uses `path-to-regexp` behind the scenes.
