### ISSUE TITLE
Navlink active classes is not working onchange of tab

### ISSUE THREAD

**Issue by numino-deepika** [react-bootstrap/react-router-bootstrap#236]
react-router-dom: 4.3.1,
 react-dom: 16.4.0,
<Menu>
					<MenuItem
						leftIcon={<Dashboard />}
						key={3}
						containerElement={<NavLink exact to="/dashboard" activeStyle={this.active}></NavLink>}
						primaryText="Dashboard"
					/>
					<MenuItem
						leftIcon={<Devices />}
						key={4}
						containerElement={<NavLink  to="/licenses" activeStyle={this.active}></NavLink>}
						primaryText="Licenses Management "
					/>
					<MenuItem
						leftIcon={<Group />}
						key={5}
						containerElement={<NavLink className='link-active' to="/users" ></NavLink>}
						primaryText="Users"
					/>
				</Menu>
here navlink active class is not working on selection of tab

**Comment by victoria34** [comment]
Hello, I have the same issue. Could you tell me how to solve this issue?
