### ISSUE TITLE
MenuItemLink inside DropDownButton on Navbar

### ISSUE THREAD

**Issue by jvillasante** [react-bootstrap/react-router-bootstrap#24]
In my navbar I have a dropdown button with options, however, when I click on a MenuItemLink on the dropdown, the route works as expected, but the dropdown is still visible even after the route changes. Here's my code:

```javascript
        <Navbar ref="header" className="navbar navbar-inverse" brand={brand} fixedTop={true} fluid={true} toggleNavKey={1}>
          <Nav className="navbar-left" eventKey={1}>
            <NavItemLink to="dashboard" eventKey={2}>Dashboard</NavItemLink>
            <DropdownButton eventKey={3} title="Admin">
              <MenuItemLink to="users" eventKey={4}>Users</MenuItemLink>
              <MenuItemLink to="projects" eventKey={5}>Projects</MenuItemLink>
            </DropdownButton>
          </Nav>
        </Navbar>
```

**Comment by tjwebb** [comment]
> but the dropdown is still visible even after the route changes. 

Also experiencing this exact same problem.

**Comment by mtscout6** [comment]
So, it's not collapsing?

**Comment by mtscout6** [comment]
Sounds like react-bootstrap/react-bootstrap#368 is the root cause of this.

**Comment by tjwebb** [comment]
Yep I just saw that too. I guess we'll chase it down over there. Thanks

**Comment by wlr** [comment]
this is still a problem, solutions? 
im using:
    "bootstrap": "3.3.2",
    "react": "0.13.1",
    "react-bootstrap": "0.19.0",
    "react-router": "0.13.2",
    "react-router-bootstrap": "0.11.0"

**Comment by CTAPbIuMABP** [comment]
+1

**Comment by andrerpena** [comment]
@CTAPbIuMABP , thanks for your reply but removing `MenuItemLink` is not the point here, and passing `onSelect={()=>{}}` makes the link stop working at all.

**Comment by CTAPbIuMABP** [comment]
i guess we have a big misunderstanding or you are just kidding me

1 nobody asks to remove MenuItemLink only remove line 23 from that file

2 by passing `onSelect={()=>{}}` you are getting to point by calling parent node's onSelect handler 
you can check it in https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownButton.js#L92

**Comment by Torwori** [comment]
So, any hacks around this until it gets fixed?

**Comment by mtscout6** [comment]
I'm sorry for the huge delay on this guys. I've been able to make some huge headway on react-bootstrap/react-bootstrap#526 over the last two weeks and I'm nearly done. Otherwise I don't have any major workarounds at the moment.

**Comment by AlexKVal** [comment]
Superceded by #526

**Comment by mathieumg** [comment]
> Superceded by #526

Link: https://github.com/react-bootstrap/react-bootstrap/issues/526

**Comment by AlexKVal** [comment]
Thank you for fixing me :cherries:
