### ISSUE TITLE
Is this project no longer being maintained?

### ISSUE THREAD

**Issue by CharlyJazz** [react-bootstrap/react-router-bootstrap#240]

**Comment by jquense** [comment]
Sometimes things can done, it's not the samething as abandoned

**Comment by CharlyJazz** [comment]
And why are there no answers on the issues? Or public relations do not mix?

**Comment by jquense** [comment]
We dont really provide support via issues and of the **two** open PRs one is not correct and on the author to fox and the other is readme tweak opened last week
