### ISSUE TITLE
LinkContainer NavItem wont scroll restore

### ISSUE THREAD

**Issue by wvazquez** [react-bootstrap/react-router-bootstrap#244]
I am trying to implement a navigation for a website. When I wrap LinkContainer around NavItem the scroll restoration wont work but the proper active styles will properly apply.

```javascript
<NavBar>
     <Navbar.Collapse>
          <Nav pullRight>
          {
            this.state.navigationList.map((item,index) =>
            <LinkContainer to={"/"+item} key={index}>
                <NavItem >
                  {item}
                </NavItem>
            </LinkContainer>
            )
          }
          </Nav>
      </Navbar.Collapse>
</Navbar>
}
```

But when I use NavItem without LinkContainer, the scroll restoration will work but the active styles wont apply as usual. 

```javascript
  <NavBar>
    <Navbar.Collapse>
          <Nav pullRight>
          {
            this.state.navigationList.map((item,index) =>

                <NavItem href={"/"+item} key={index}>
                  {item}
                </NavItem>
            
            )
          }
          </Nav>
        </Navbar.Collapse>
      </Navbar>
```

Please let me know if i am missing something. Thanks!

**Comment by taion** [comment]
If you're using React Router, you'll need to set up scroll restoration _in_ the router. You'd get the same behavior with any router link.

**Comment by wvazquez** [comment]
Yes I am using react router and currently have it said up this way

```javascript
<BrowserRouter >
        <ScrollToTop>
          <Switch>
            <Route exact path="/" component={ComingSoon}/>
            <Route exact path="/Home" component={Home}/>
            <Route path="/About" component={About}/>
            <Route path="/Contact" component={Contact} />
            <Route exact path={"/Work"} component={Categories} />
            <Route path={`/Work/:project`} component={Projects} />
          </Switch>
        </ScrollToTop>
    </BrowserRouter>
```

Where scrollToTop is the set up just as describe in [React Router](https://reacttraining.com/react-router/web/guides/scroll-restoration)
This works only when I don't use LinkContainer, but then no active styles on my navigation get applied.
