### ISSUE TITLE
Whitespace does not behave consistently

### ISSUE THREAD

**Issue by joe-oli** [react-bootstrap/react-router-bootstrap#245]
Version: 0.24.4

Following usage crashes.
```
<Nav>
	<LinkContainer to="/fax"><NavItem>My menu item</NavItem>  </LinkContainer>
</Nav>
```
Note the trailing space or spaces after closing NavItem tag. 
With any whitespace either before or after NavItem tag, the page crashes / does not build, the cryptic error message is; "React.Children.only expected to receive a single React element child."

Once I did a carriage return and moved closing LinkContainer tag on its own line, error is gone (even though I did not remove the trailing space/s after closing NavItem. Both the below work.

```
<Nav>
         <LinkContainer to="/fax"><NavItem>Ad-hoc Check</NavItem>   (white space here)
         </LinkContainer>
</Nav>

<Nav>
	<LinkContainer to="/fax">
		<NavItem>My menu item</NavItem>
	</LinkContainer>
</Nav>
```
Expected. Should behave like html and ignore all white spaces whether all on one line or across separate lines.

**Comment by taion** [comment]
Those are just the semantics around whitespace in JSX. See https://reactjs.org/docs/jsx-in-depth.html.
