### ISSUE TITLE
Version 1.0 (react-bootstrap) support?

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-router-bootstrap#246]
Hey,

is this package still supporting react-boostrap version 1.0?

Otherwise we have to add some notes for that :)

Best regards

Max

**Comment by jquense** [comment]
hi there, not sure specifically what you mean by version 1.0, the current version is 1.0, it supports bootstrap 4, the previous version is 0.32.0 which supports bootstrap v3

**Comment by taion** [comment]
i think asking about support for react-bootstrap v1

**Comment by jquense** [comment]
that's the current version tho?

**Comment by taion** [comment]
i mean the answer here in any event is "yes", because this library actually has nothing to do with react bootstrap any more, except for naming.

really we should just rename this to react-router-link-container and move this out or something

**Comment by jquense** [comment]
bah sorry i always fail to see that this isn't the react-bootstrap repo :( i see how i sound stupid :P

**Comment by mxschmitt** [comment]
Oh okay. So this library is still supporting the current `react-bootstrap` version. Because I migrated a project with version 0.32 to version 1.0 at work and replaced it by other ways of adding links / hrefs.
