### ISSUE TITLE
No Examples for React-Router

### ISSUE THREAD

**Issue by tuppers360** [react-bootstrap/react-router-bootstrap#254]
Hi raising the issue due to spending some time looking at why React-Bootstrap was doing a full re-render when following the documentation to the letter involving the Navbar and Nav.Link.

There is no mention in the documentation about using react-router-bootstrap to use LinkContainer to help solve the issue of a full re-render and then when coming here (directed by a good egg {Brady.#2138} on discord) there is very little about LinkContainer. I appreciate this may not be the case as I am no expert but from a learning point this was very difficult.

So in essence a few Sandbox examples would go along way and/or updated documentation re the LinkContainer in the react-bootstrap documentation would really help!

Thanks

**Comment by gergelyszabo94** [comment]
I found out about this package after searching for solutions on the <Nav.Link> re-render too. I don't think anything has changed since you opened this issue.
