### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by tjwebb** [react-bootstrap/react-router-bootstrap#27]
When I click on normal `<Link>` components, routing works fine. When I click on a `<MenuItemLink>` configured exactly the same way, the route does change, but I see this error in the console:
```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
```

**Comment by mtscout6** [comment]
Do you have a stack trace or any more contextual information that would isolate the issue?
