### ISSUE TITLE
react-router-bootstrap LinkContainer wrapping a Nav.Link incompatible with latest react-router-dom v.6.0.2

### ISSUE THREAD

**Issue by silveriordza** [react-bootstrap/react-router-bootstrap#273]
I have this code:
 <Navbar.Collapse id='basic-navbar-nav'>
            <Nav className='me-auto'>
              <LinkContainer to='/'>
                <Nav.Link>Home</Nav.Link>
              </LinkContainer>

After npm start to open the webpage in a Chrome browser, the browser shown this error:

TypeError: (0 , _reactRouterDom.withRouter) is not a function ./node_modules/react-router-bootstrap/lib/LinkContainer.js

S:/Kuarsis/webapps/kuarsis/frontend/node_modules/react-router-bootstrap/lib/LinkContainer.js:155
  152 |   strict: false,
  153 |   activeClassName: 'active'
  154 | };
> 155 | exports.default = (0, _reactRouterDom.withRouter)(LinkContainer);

I ran this commands to fix it:

npm uninstall react-router-dom    -> I had the latest version installed 6.0.2

Then run this command:

npm i react-router-dom@5.0.0   -> I forced it to install the older version 5.0.0

After running "npm start" again, the webpage worked just fine and opened as expected in Chrome, the reactRouterDom issue didn't show up. 

I'm not sure whether the way of coding this LinkContainer while using react-router-dom 6.0.2 changed and I'm doing something wrong, OR the LinkContainer is just not compatible with that version of react-router-dom 6.0.2.  Please comment or let me know if this is a bug to be fixed. Thanks!

**Comment by silveriordza** [comment]
![Capture](https://user-images.githubusercontent.com/63380676/143297993-d72846a9-ad27-4af7-8627-4df656445edc.JPG)

The code I have didn't render properly in the issue description I sent above, so I'm sending the image here, I hope this helps.

**Comment by kyletsang** [comment]
See https://github.com/react-bootstrap/react-router-bootstrap/issues/266
