### ISSUE TITLE
LinkContainer doesn't actually support NavLink props (className, style)

### ISSUE THREAD

**Issue by bfricka** [react-bootstrap/react-router-bootstrap#274]
`NavLink` allows functions to be passed for `className` and `style`

```tsx
<LinkContainer
  to=""
  className={(isActive) => `btn-${isActive ? 'primary' : 'link'}`}
  style={(isActive) => isActive ? activeStyle : defaultStyle}
>
  <Button>Foo</Button>
</LinkContainer>
```

Unfortunately, `LinkContainer` trips on prop types and coerces the functions to string. This should be extremely easy to support. I can add it if you want.

**Comment by kyletsang** [comment]
PRs welcome, thanks

**Comment by bfricka** [comment]
I meant this to be related to RRv5. I went to fix this, but realized we're currently on v6 support and since this project is at 0.x versions, I'm not sure how I'd add it to RRv5. In RRv6 `activeClassName` and `activeStyle` are not even valid props, so the way it's written now is a little confusing, active modifiers are only supported via `className|style`-as-function.

It would be nice if this package had React Router support segmented by major versions, but since it doesn't, I'm not really sure what to do. I'll likely rewrite my own version for now, but I'm willing to help if you want to come up with a game plan moving forward.
