### ISSUE TITLE
DropdownButton onSelect not fired when MenuItemLink is clicked

### ISSUE THREAD

**Issue by loktar00** [react-bootstrap/react-router-bootstrap#30]
Noticing if you set the `onSelect` for the `DropdownButton` along with a `<MenuItem>` element the event is fired, however when using a `<MenuItemLink>` the `onSelect` doesn't seem to fire.

**Comment by mtscout6** [comment]
I've been getting a lot of reports of bugs with the dropdown, both here and in react-bootstrap. I don't have time this week, or even next to deal with it. I am open to pull requests, so if you are able to figure it out I'd love a fix.

**Comment by SudoPlz** [comment]
I've got the same problem as well.. No solution found yet.

**Comment by taion** [comment]
I believe this is superseded by https://github.com/react-bootstrap/react-bootstrap/issues/526. Can we close this?

**Comment by mtscout6** [comment]
Yes #526 will account for this.
