### ISSUE TITLE
bower.json is out of sync

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-router-bootstrap#34]
The `bower.json` file has the wrong version (`"0.8.3"`) and still lists dependencies as:

```JSON
  "dependencies": {
    "react-router": "^0.11.6",
    "react-bootstrap": "^0.13.2"
  }
```

Specifically these conflict with the most recent versions of those packages, while the dependency versions specified in `package.json` don't.

**Comment by mtscout6** [comment]
Resolved by #47
