### ISSUE TITLE
classnames as peer dependency

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-router-bootstrap#41]
Why is classnames set up as a peer dependency rather than a normal dependency? Seems like it'd be neater, and it'd be one less warning from npm about how the behavior will change in npm 3+.

**Comment by mtscout6** [comment]
Sounds reasonable to change, will take a PR.

**Comment by taion** [comment]
Will do. Do you want to stay with classnames 1.x.x to not lose IE8 compat w/o polyfill?

**Comment by mtscout6** [comment]
I'm fine with taking the latest version of classnames and add documentation in the README that a polyfill is required for IE8. This is no different than react-bootstrap anyways, see: http://react-bootstrap.github.io/getting-started.html#browser-support

**Comment by dozoisch** [comment]
I'm totally with @mtscout6. We shouldn't drawing ourselves back too much when people can just polyfill.

**Comment by mtscout6** [comment]
@taion Did you want to include this in #46? If so we can wait for it.

**Comment by mtscout6** [comment]
@taion Nevermind I see you just pushed a commit.

**Comment by taion** [comment]
I had noticed after submitting the PR that you updated react-bootstrap to use 2.x.x, so it's only reasonable to make this package consistent.
