### ISSUE TITLE
Transfer repo to react-bootstrap organization

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-router-bootstrap#42]
I have been focusing my efforts of late on react-bootstrap to fix a number of bugs there, in pursuit of a 1.0.0 release. This repo has grown much more than I had originally anticipated, and I would like to propose moving it to the [react-bootstrap](https://github.com/react-bootstrap) organization. Doing so would allow to have more collaborators to help in it's maintenance so PRs and issues are not left unattended due to lack of time on my part. In doing so, I'd like to adopt the Collaborating and Maintaining documentation as already stated in react-bootstrap.

With this change I'd like to invite the existing collaborators of this repo to be in the react-bootstrap organization to retain their current status with this project. Which includes the current collaborators:

- @vespakoen 
- @idolizesc 
- @dozoisch (already a member of react-bootstrap)

Are there any objections by the @react-bootstrap/collaborators team?

- @joemcbride
- @AlexKVal
- @mathieumg
- @apkiernan
- @dozoisch 
- @aabenoja

If I see no objections by May 5th, 2015 14:00 GMT then I'll plan to proceed.

I will plan to retain a link in the readme at the current project's url to the transferred repo.

**Comment by joemcbride** [comment]
:+1: Seems like a good idea to me.

**Comment by mathieumg** [comment]
:+1: The more, the merrier!

**Comment by aabenoja** [comment]
:+1: More power to the org.

**Comment by AlexKVal** [comment]
This project has been created for use with `react-bootsrap`, then it was just a matter of time to move it into the organisation :+1:

**Comment by dozoisch** [comment]
:+1:
