### ISSUE TITLE
DropdownButton not set to active when navitem child link is active route

### ISSUE THREAD

**Issue by vipero07** [react-bootstrap/react-router-bootstrap#44]
If you click a link in a navbar menu the link is marked active appropriately but the drop down button is not. EX:
```jsx
<DropdownButton title="Menu1" navItem>
	<MenuItemLink to="item1">item1</MenuItemLink>
	<MenuItemLink to="item2">item2</MenuItemLink>
	<MenuItemLink to="item3">item3</MenuItemLink>
</DropdownButton>
```
When clicking item1 it will put the active class on item1's li but not on the class for Menu1's tag.

A less than ideal (due to speed), yet functional solution is this
```javascript
var DropdownButton = require('react-bootstrap').DropdownButton;

var DropdownButtonLink = React.createClass({
    mixins: [State],
    render: function(){
        var activeClass;
        React.Children.forEach(this.props.children, function(child){
            if(this.isActive(child.props.to,child.props.params,child.props.query)){
                activeClass = "active";
            }
        }, this);
        return (
            <DropdownButton {...this.props} className={activeClass}/>
        );
    }
});
```

**Comment by vipero07** [comment]
Modified the solution to handle MenuItem dividers (and other items inside the menu that are not react-router links)

```jsx
var DropdownButton = require('react-bootstrap').DropdownButton;

var DropdownButtonLink = React.createClass({
    mixins: [State],
    render: function(){
        var activeClass;
        React.Children.forEach(this.props.children, function(child){
            if(child.props.to && this.isActive(child.props.to,child.props.params,child.props.query)){
                activeClass = "active";
            }
        }, this);
        return (
            <DropdownButton {...this.props} className={activeClass}/>
        );
    }
});
```
Essentially it is just checking for child.props.to to make sure it doesn't try to check for an invalid route.

**Comment by mtscout6** [comment]
I'm in the middle of re-writing the DropdownButton once that's complete let's revisit this bug. See react-bootstrap/react-bootstrap#526 for details of that progress.

**Comment by vipero07** [comment]
I'm not sure those changes would affect this but I'm not in a particular rush to have it fixed as that proposed solution (though not the best) functions well enough for my uses. I'll probably fiddle around a bit to for a better solution using either a flux pattern or passing a function to the children that sets a state of the dropdownbutton parent similar to what the react docs say here https://facebook.github.io/react/tips/communicate-between-components.html

Truthfully I just didn't want to have to write a new dropdown button and menu item link component that inherit the originals because of lazyness.

**Comment by mtscout6** [comment]
Ah, I'm understanding you now. Yes, the two are not related.

**Comment by AlexKVal** [comment]
Pull requests are welcome :wink:

**Comment by taion** [comment]
`LinkContainer` is active on all subroutes now.

**Comment by jure** [comment]
Seems it's too eager to be active now? I.e. both 'Share' and 'Manage' LinkContainers are active for me:

![image](https://cloud.githubusercontent.com/assets/238667/10163147/0cb76bfe-66b1-11e5-907a-2255364e8792.png)

And 'Manage' is not a subroute of 'Share':

```
  <Route component={App}>
    <Route path='/' component={Share}/>
    <Route path='/admin'>
      <Route path='manages' component={Manage} />
      <Route path='about' component={About} />
    </Route>
  </Route>
```

**Comment by taion** [comment]
That's just how React-Router defines `active`. Use `IndexLinkContainer` if you need more specificity.

**Comment by cwbuecheler** [comment]
I have a setup with a Navbar. eg:

Dashboard | About Us | Contact

Where the "Dashboard" section then has a sidebar with sub-navigation. But my routes are not sub-routes of /dashboard. As a result, the "Dashboard" item in the menu is only active when the path is "/dashboard" and not, for example, when it's "/devices" ... I know there's an argument to be made that this is not semantically correct, but it's the client's preference.

Is there any way to override how <LinkContainer> sets a NavItem to be active or not, and control it manually, so that I can force "Dashboard" to be active with a wide variety of paths?

**Comment by jeffhoang** [comment]
I also have this issue...I've tried viper's hack, but it didn't work.

**Comment by cmatteri** [comment]
I have a navbar with a dropdown that's essentially the same as jeffhoang's example. When I click the dropdown, the route is immediately changed to /products, before I select an item from the dropdown. Setting the NavDropdown's LinkContainer's onClick prop to ```{(event) => event.preventDefault()}``` is sufficient to prevent the route from changing until I select an item from the dropdown.

Is this the correct behavior? If it is, setting onClick works just fine, but I'm surprised that I haven't seen it in any examples.

**Comment by ViggoV** [comment]
Thanks for the hack (or what to call it), @cmatteri. Saved my day :)

**Comment by eslamibrahimhamed** [comment]
function NavbarComp() {
  const [active, setActive] = useState("1");
  const [dropdownOpen, setDropdownOpen] = useState(false);

  const toggleDropdown = () => setDropdownOpen(!dropdownOpen);

  const toggle = (tab) => {
    setActive(tab);
  };

  return (
    <div>
      <Navbar bg="dark" variant={"dark"} expand="lg" fixed="top">
        <Navbar.Toggle aria-controls="navbarScroll" />
        <Navbar.Collapse id="navbarScroll">
          <Nav
            className="mr-auto my-2 my-lg-0 container"
            style={{ maxHeight: "100px" }}
            navbarScroll
          >
            <Navbar.Brand href="/">LOGO</Navbar.Brand>
            <NavLink
              to="/"
              style={{ color: "#FFF" }}
              active={active === "1"}
              onClick={() => {
                toggle("1");
              }}
            >
              Home
            </NavLink>
            <NavLink
              to="/about"
              style={{ color: "#FFF" }}
              active={active === "2"}
              onClick={() => {
                toggle("2");
              }}
            >
              About
            </NavLink>
            <NavLink
              to="/contact"
              style={{ color: "#FFF" }}
              active={active === "3"}
              onClick={() => {
                toggle("3");
              }}
            >
              Contact
            </NavLink>
            <div>
              <div
                id="drop"
                isopen={dropdownOpen}
                toggle={toggleDropdown}
                className={classnames({
                  active: active === "active",
                })}
              >
                <span id="d-link">Dropdown link</span>

                <div
                  className="dropdown-menu "
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <section className="d-flex">
                    <div>
                      <NavLink
                        className="dropdown-item"
                        to="/test"
                        active={active === "active"}
                        onClick={() => {
                          toggle("active");
                        }}
                      >
                        Action
                      </NavLink>
                      <NavLink
                        className="dropdown-item"
                        to="/test1"
                        active={active === "active"}
                        onClick={() => {
                          toggle("active");
                        }}
                      >
                        Another action
                      </NavLink>
                      <NavLink
                        className="dropdown-item"
                        to="/test2"
                        active={active === "active"}
                        onClick={() => {
                          toggle("active");
                        }}
                      >
                        Something else here
                      </NavLink>
                    </div>
                    <div>
                      <NavLink
                        className="dropdown-item"
                        to="/test3"
                        active={active === "active"}
                        onClick={() => {
                          toggle("active");
                        }}
                      >
                        Action
                      </NavLink>
                      <NavLink
                        className="dropdown-item"
                        to="/test4"
                        active={active === "active"}
                        onClick={() => {
                          toggle("active");
                        }}
                      >
                        Another action
                      </NavLink>
                      <NavLink
                        className="dropdown-item"
                        to="/test5"
                        active={active === "active"}
                        onClick={() => {
                          toggle("active");
                        }}
                      >
                        Something else here
                      </NavLink>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </Nav>
        </Navbar.Collapse>
      </Navbar>
    </div>
  );
}

export default NavbarComp;
