### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-router-bootstrap#48]
- [ ] Bower Need to create a new repo for the bower release, similar to what we are doing in react-bootstrap today. The goal being to stop committing compiled code to the repo.
- [x] Changelog generation
- [x] Remove `lib/` folder from this repo

It may make sense to extract some of the tooling in react-bootstrap to a separate repo for this.

**Comment by AlexKVal** [comment]
I'm on it.

Could somebody create new `react-router-bootstrap-bower` repo for this ?

I got already working release tool, that I've checked on trash ES6 project.
https://github.com/AlexKVal/es6-prototype-proj-bower/releases
https://www.npmjs.com/package/es6-prototype-proj
https://github.com/AlexKVal/es6-prototype-proj/releases

It has `verbose` and `dry-run` modes too. :sparkle: 

I made that changelog generated messages are adding as git tag message, like this:
<img width="1003" alt="git tag" src="https://cloud.githubusercontent.com/assets/847572/8604504/abf09f98-2687-11e5-9db0-ec42cc0b87b7.png">

**Comment by dozoisch** [comment]
@taion ? maybe you can create the repo! 

Awesome work Alex

**Comment by taion** [comment]
In transit at the moment. Will attend to this after flight lands.

**Comment by AlexKVal** [comment]
Again: /cc @react-bootstrap/collaborators
Could anyone, please, create new `react-router-bootstrap-bower` repo for this ? :smile: 
#87 closes this issue.

**Comment by taion** [comment]
Repo created.
