### ISSUE TITLE
Issue when including as vendor in webpack

### ISSUE THREAD

**Issue by dfoverdx** [react-bootstrap/react-router-bootstrap#51]
I'm having an issue including react-router-bootstrap in my vendors.js output of my webpack.config.js.

My config looks like this:

    var Webpack = require('webpack');
    var VENDOR_PATH = __dirname + '/node_modules';
    var CommonsChunkPlugin = Webpack.optimize.CommonsChunkPlugin;

    var config = {
        /* for vendors (and other modules) we have a CDN for */
        addExternal: function (name, globalVar) {
            this.externals[name] = globalVar;
            this.entry.vendors.push(name);
        },

        /* for vendors we don't have a CDN for */
        addVendor: function (name, path) {
            this.resolve.alias[name] = path;
            this.entry.vendors.push(name);
        },

        addPlugin: function (plugin) {
            this.plugins.push(plugin);
        },

        entry: {
            app: [ './src/main.js' ],
            vendors: [],
        },

        plugins: [],

        externals: { },

        output: {
            path: __dirname + '/public/dist',
            filename: 'bundle.js'
        },

        resolve: {
            alias: { },
            extensions: [ '', '.js', '.jsx' ]
        },

        module: {
            noParse: [],
            loaders: [
                { test: /\.less$/, loader: 'style-loader!css-loader!less-loader', exclude: /node_modules/ },
                { test: /\.jsx?$/, loader: 'babel-loader?stage=0', exclude: /node_modules/ },
            ]
        }
    };

    config.addExternal('jquery', 'jQuery');
    config.addExternal('react', 'React');

    config.addVendor('react-router', VENDOR_PATH + '/react-router/umd/ReactRouter.js')
    config.addVendor('react-bootstrap', VENDOR_PATH + '/react-bootstrap/dist/react-bootstrap.js');
    config.addVendor('react-router-bootstrap', VENDOR_PATH + '/react-router-bootstrap/lib/index.js');

    config.addPlugin(new CommonsChunkPlugin('vendors', 'vendors.js'));

    module.exports = config;

The error I'm getting is caused by lines like this:

    var Button = require('react-bootstrap/lib/Button');

Error:

    ERROR in ./~/react-router-bootstrap/lib/ButtonLink.js
    Module not found: Error: Cannot resolve 'file' or 'directory' c:\[...]\project/node_modules/reactbootstrap/dist/react-bootstrap.js/lib/Button in c:\[...]\project\node_modules\react-router-bootstrap\lib
     @ ./~/react-router-bootstrap/lib/ButtonLink.js 3:13-50

Changing the line to this fixes it:

    var Button = require('react-bootstrap').Button;

I'm new to javascript development so I don't know if this is the proper fix/workaround or if I'm even setting up my webpack project correctly.

Thoughts?

**Comment by taion** [comment]
You need to use `ReactRouterBootstrap.js` (or the minified version) instead of `index.js`. The former is the fully built distributable version; the latter isn't.

**Comment by dfoverdx** [comment]
That's actually what I tried first.  I've switched it back to that file, and I now get these errors.

ERROR in ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' d:\src\dmtables\pr
oject/node_modules/react-bootstrap/dist/react-bootstrap.js/lib/MenuItem in d:\sr
c\dmtables\project\node_modules\react-router-bootstrap\lib
 @ ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js 1:137-176

ERROR in ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' d:\src\dmtables\pr
oject/node_modules/react-bootstrap/dist/react-bootstrap.js/lib/Button in d:\src\
dmtables\project\node_modules\react-router-bootstrap\lib
 @ ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js 1:99-136

ERROR in ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' d:\src\dmtables\pr
oject/node_modules/react-bootstrap/dist/react-bootstrap.js/lib/NavItem in d:\src
\dmtables\project\node_modules\react-router-bootstrap\lib
 @ ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js 1:177-215

ERROR in ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' d:\src\dmtables\pr
oject/node_modules/react-bootstrap/dist/react-bootstrap.js/lib/ListGroupItem in
d:\src\dmtables\project\node_modules\react-router-bootstrap\lib
 @ ./~/react-router-bootstrap/lib/ReactRouterBootstrap.min.js 1:216-260

**Comment by taion** [comment]
I see... I haven't worked with setting these up as externals, but you might want to try copying over these external definitions: https://github.com/react-bootstrap/react-router-bootstrap/blob/master/webpack.config.js#L48-L78
