### ISSUE TITLE
NavItemLink not closing after click

### ISSUE THREAD

**Issue by andrerpena** [react-bootstrap/react-router-bootstrap#60]
Hi.
Thanks for the awesome work.
I'm trying react-router-bootstrap with react-starter right now and I noticed that NavItemLink it's not closing after I click it. I mean, it's actually working, but it's not closing.
Is it something obvious? Or do you need implementation details?
I really appreciate the help.

**Comment by andrerpena** [comment]
My guess is that the click is not changing the menu state.. so react-router re-renders but the "open" state persists.

**Comment by mtscout6** [comment]
I'm presuming that you mean it does not work when the Navbar is rendered in a mobile view? Because otherwise NavItems in general are not in a dropdown unless that is the case.

**Comment by mtscout6** [comment]
We'd take a PR to fix this. Though it may be related to react-bootstrap/react-bootstrap#419 and require a fix in react-bootstrap first.

**Comment by andrerpena** [comment]
Thanks for the response.

I'm not on Mobile, I'm just using the default NavBar from React-Bootstrap, the one with a dropdown menu: http://react-bootstrap.github.io/components.html#navbars

Screenshot:

![image](http://i.imgur.com/goeHJ9s.png)

**Comment by mtscout6** [comment]
If it's with the dropdown than it's a duplicate of #24
