### ISSUE TITLE
Nav must have onSelect in order to prevent page transition

### ISSUE THREAD

**Issue by kirill-konshin** [react-bootstrap/react-router-bootstrap#61]
The following setup w/o `onSelect` handler will not work -- it will make the actual page transition (not handled by router) when NavItem is clicked...

```jsx
                    <Nav bsStyle='pills' onSelect={()=>{}} justified>
                        <NavItemLink to="country" disabled>Country</NavItemLink>
                    </Nav>
```

**Comment by wavded** [comment]
I'm experiencing something similar, although setting `onSelect` doesn't seem to help either.  The event isn't triggered when using a `NavDropdown` with `MenuItemLink` elements.

**Comment by taion** [comment]
@wavded That's most likely #112 instead.

@kirill-konshin We need to handle `props.onClick` on `NavItem` on React-Bootstrap I think.

**Comment by taion** [comment]
Combining this into #112.
