### ISSUE TITLE
The package react-bootstrap does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by bazo** [react-bootstrap/react-router-bootstrap#62]
$ npm install --save react-router-bootstrap
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-router-bootstrap"
npm ERR! node v1.2.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-bootstrap does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router-bootstrap@0.15.0 wants react-bootstrap@>=0.22.4

very nice of you

**Comment by mtscout6** [comment]
Which version of react-bootstrap do you have in your project? We made a change in this library that was dependent on a change introduced in that release of react-bootstrap. Which is also why the release for react-rotuer-bootstrap was a Minor version bump which in pre 1.0 terms is a breaking change version bump.

**Comment by bazo** [comment]
i guess the latest, since i first copy pasted the line from installation
instructions. btw why is it missing to install the actual
react-router-bootstrap package?

**Comment by mtscout6** [comment]
That doesn't answer the question of which version. Can you run `npm ls --depth=0` and tell me what you see?

**Comment by bazo** [comment]
this won't help since i already fix it, by uninstalling those packages and
running only npm install react-router-bootstrap which in turn also
installed the required version of the other packages

**Comment by dozoisch** [comment]
react-router-bootstrap has a peer dep on react-bootstrap to avoid having two different versions. So it doesn't have the dependency by itself. You need to install react-bootstrap in your project in order to use react-router-bootstrap.

**Comment by mathieumg** [comment]
Yes, but node will install your peer deps if they aren't already there.

**Comment by taion** [comment]
This is just how NPM handles peer dependencies. If you've already got R-B installed and you're installing R-R-B, I guess it's up to you to make sure that your version of R-B satisfies R-R-B's `peerDependencies`.
