### ISSUE TITLE
Activate items when on subroutes

### ISSUE THREAD

**Issue by Industrial** [react-bootstrap/react-router-bootstrap#63]
Hi.

I'm using `react-router` and `<NavItemLink key={i} eventKey={i} to={v.href} params={params} query={query}>{v.label}</NavItemLink>`. When I go to the intended route e.g. `#/cms/users` it will highlight the Users entry (which is the value of `v.href`). When I go to `#/cms/users/someId/anythingreally` then the menu item will be deselected.

How can I select a NavItemLink's active state based on the URL/Route?

**Comment by mtscout6** [comment]
There is a limitation with the underlying MenuItem. This is a known bug due to react-bootstrap/react-bootstrap#443

**Comment by taion** [comment]
`LinkContainer` is active on all subroutes now.
