### ISSUE TITLE
Implement eslint linting

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-router-bootstrap#69]
As a start point these are the lines from the old (long unused) code:
```js
jshint: {
  enforceall: true,
  // jsx splat will make this fail
  eqnull: true,
  camelcase: false,
  nocomma: false,
  browser: true,
  singleGroups: false,
  emitErrors: true,
  failOnHint: true
}
```

**Comment by mtscout6** [comment]
I assume this is only for codeclimate or bithound?

**Comment by mtscout6** [comment]
Nevermind I just realized that you took this out of the old webpack.config file. I'd rather use eslint, with a similar configuration to react-bootstrap.

**Comment by AlexKVal** [comment]
Yeah. I thought about eslint too. Just forgot to mention it here.

**Comment by taion** [comment]
:+1:
