### ISSUE TITLE
npm up - peerinvalid error.

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-router-bootstrap#70]
```
$ npm up
...
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-bootstrap@0.23.2 wants react@>=0.13
npm ERR! peerinvalid Peer react-router@0.13.3 wants react@0.13.x
```

**Comment by dozoisch** [comment]
thats seems like a bug in npm u_U 0.13.x and 0.13 is pretty much the same unless react-0.14 is out

**Comment by mathieumg** [comment]
Indeed, the both highlight `0.13.0` through `0.13.3` on http://semver.npmjs.com/

**Comment by AlexKVal** [comment]
> unless react-0.14 is out 

indeed
![screen shot 2015-06-09 at 9 04 03 pm](https://cloud.githubusercontent.com/assets/847572/8065602/21804376-0eeb-11e5-9d2e-7707b9df5108.png)

**Comment by AlexKVal** [comment]
anyway I gave it more thought..
the clean installation works fine, I'm closing.
```sh
$ rm -rf node_modules
$ npm run i
```

**Comment by AlexKVal** [comment]
It seems this is the cause why `react-router` sets `react` dependency that way: `react@0.13.x`

**Comment by dozoisch** [comment]
We should do the same since any react updates are pretty majors right now.

**Comment by AlexKVal** [comment]
I've found the culprit.
It is this line: `"react": "*"` [package.json#L54](https://github.com/react-bootstrap/react-router-bootstrap/blob/9187a30e6613f85fbee5980e8f3d683c02ec298d/package.json#L54)

If I change it to `"react": ">0.10.0"` then everything is fine.

I've got a question before I can PR this change.
What is the minimal sufficient version of react here ?

**Comment by taion** [comment]
Should be `0.13.x` I'd think?

**Comment by AlexKVal** [comment]
maybe for the benefit of safety `>0.10.0` ?

though I presume those who has active React projects - in theory - has to update them already at least to 0.12

but we still can just for safety set it to `>0.10.0`

**Comment by mathieumg** [comment]
Theoretically, the lower that doesn't break it!

**Comment by catskul** [comment]
This has cropped up again

I'm not sure if it's somehow configuration dependent, but if I create a new directory, and attempt to install react-bootstrap locally I consistently get `peerinvalid` for all versions that I've tested (0.18, 0.19, HEAD)

Example:

```
catskul$ npm install react-router-bootstrap@0.18
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN peerDependencies The peer dependency react-bootstrap@>=0.22.4 included from react-router-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-router@>=0.13.1 included from react-router-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@0.13.x included from react-router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@>=0.14.0 included from react-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@>=0.14.0 included from react-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@>=0.11.0 included from uncontrollable will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@>=0.14.0 included from react-overlays will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@^0.14.0 included from react-overlays will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 3.16.0-44-generic
npm ERR! argv "/home/catskul/.nvm/versions/io.js/v2.0.2/bin/iojs" "/home/catskul/.nvm/versions/io.js/v2.0.2/bin/npm" "install" "react-router-bootstrap@0.18"
npm ERR! node v2.0.2
npm ERR! npm  v2.9.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@0.13.4 wants react@0.13.x
npm ERR! peerinvalid Peer react-bootstrap@0.27.2 wants react@>=0.14.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/catskul/tmp/test-react-bootstrap/npm-debug.log
```

**Comment by taion** [comment]
You can see the error in your own logs:

```
npm ERR! peerinvalid Peer react-router@0.13.4 wants react@0.13.x
npm ERR! peerinvalid Peer react-bootstrap@0.27.2 wants react@>=0.14.0
```

And RRB v0.19.x requires a React Router v1.0.0 prerelease anyway.

**Comment by catskul** [comment]
Not sure I understand. How should installing a single package locally in a fresh local dir (no other installs done) ever create a peerinvalid error?

**Comment by taion** [comment]
You have two packages that require incompatible peer dependencies.

**Comment by catskul** [comment]
But they're pulled in by react-router-bootstrap. I did not specify those packages.

**Comment by taion** [comment]
Oh. I see. Unfortunately that's just NPM2's peer dependency handling for you - you'll need to explicitly specify React-Bootstrap v0.26.x.

**Comment by catskul** [comment]
Apparently something I've not yet discovered, but that certainly worked. Thanks! : )

Should react-router-bootstrap not itself include dependency information to prevent this situation from happening, or is it something that is not resolvable that way?

**Comment by taion** [comment]
We'd have to cut a new v0.18.x release that explicitly excluded React Bootstrap >= v0.27.0. I'm not sure that's worth the effort.
