### ISSUE TITLE
Get rid of RouterOverlayTrigger and RouterModalTrigger

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-router-bootstrap#77]
Per https://github.com/react-bootstrap/react-bootstrap/issues/811#issuecomment-110995054

These won't actually be needed for React v0.14.

**Comment by mtscout6** [comment]
You sure that you want to remove this before 0.14 is out? Is there anybody that's using it at the moment. I'm fine with creating an issue and a React 0.14 milestone if that's the case.

**Comment by taion** [comment]
Oops, should have been more clear - I should have done more research before adding those two components, but I agree that we can't remove them until React v0.14 is out. I just wanted to get rid of the docs right now to minimize the number of users for when we do deprecate those components.

**Comment by taion** [comment]
#98 gets us halfway there.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-router-bootstrap/commit/f9117998aef791255ec1802129843a86e0a029b7
