### ISSUE TITLE
Doesn't work with latest react-router beta?

### ISSUE THREAD

**Issue by israelidanny** [react-bootstrap/react-router-bootstrap#90]
I get the following when I'm trying to install `react-router-bootstrap`:
```
npm WARN package.json eslint-config-airbnb@0.0.6 No README data
npm WARN peerDependencies The peer dependency react-router@>=0.13.1 included from react-router-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/danny/.node/bin/npm" "install" "react-router-bootstrap" "--save"
npm ERR! node v0.10.28
npm ERR! npm  v2.9.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-router does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router-bootstrap@0.17.1 wants react-router@>=0.13.1

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danny/src/bpii-next/npm-debug.log
```

This is my package.json requirement:
`"react-router": "v1.0.0-beta3"`

**Comment by taion** [comment]
Shouldn't that be `1.0.0-beta3`? i.e. without the preceding `v`?

**Comment by israelidanny** [comment]
It doesn't work either way :) Tested that.

**Comment by jquense** [comment]
my understanding is the prereleases don't match ranges so `>=` doesn't actually check the beta

**Comment by dozoisch** [comment]
We might need to change the range to something like `>=0.13 || >=1.0.0-beta`

**Comment by taion** [comment]
We actually need `<1.0.0` for the current release, since we're not compatible.

**Comment by mark2685** [comment]
Running into the same issue, any update on this?

**Comment by ariporad** [comment]
+1.

If I wanted to open a PR to add this functionality, how would I go about doing such a thing?

**Comment by jquense** [comment]
I believe ya'll might want to hold off on starting to do this. I think @taion asked the RR team if now was a good time to count on the API and they said probably not.

**Comment by taion** [comment]
What @jquense said, pretty much.

You can submit PRs against the react-router-v1.0 branch if you're so inclined, but the RR team toTHE EAGLE HAS LANDED 31 39 36 39 2f 30 37 2f 32 30 20 32 30 3a 31 38 Now is the time of tranquillity, and I shall rest and observe the Earth.
  -- Uriel4ld me to hold off on e.g. porting code and tests over.

**Comment by sebas5384** [comment]
@taion I'm trying to use the branch, but the npm isn't downloading the files, any help?
```
"react-router-bootstrap": "react-bootstrap/react-router-bootstrap#react-router-v1.0",
```

thanks!

**Comment by taion** [comment]
You probably need to manually build the package. I don't know if it actually works with RR 1 beta 3 though.

**Comment by bratva** [comment]
+1
This is my package.json requirement:
```
"react-router": "v1.0.0-beta3",
"react": "^0.14.0-beta2",
"react-bootstrap": "v0.24.5-react-pre.0"
```

Error
```
npm ERR! peerinvalid Peer react-router-bootstrap@0.18.1 wants react-router@>=0.13.1
```

**Comment by commandtab** [comment]
Any recent updates here? If work is being done for react-router 1.x compatibility, how can I help?

**Comment by rgrwkmn** [comment]
FYI I was using a really old version of npm that didn't enforce peer dependencies and react-router-bootstrap NavItemLinks were working fine with react-router 1.0.0-beta3. That's the only component I was using though.

**Comment by J22Melody** [comment]
Waiting for react-router 1.x compatibility!

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-router-bootstrap/commit/f9117998aef791255ec1802129843a86e0a029b7

**Comment by devnomad** [comment]
@taion Many thanks! :)
