### ISSUE TITLE
Why not use ~ instead of ^ in package.json?

### ISSUE THREAD

**Issue by israelidanny** [react-bootstrap/react-router-bootstrap#93]
Isn't `^` a little too all inclusive?

**Comment by jquense** [comment]
is there a specific case you think that might be a problem?

**Comment by israelidanny** [comment]
Well, literally anything in `package.json` jumping up a major version & ruining every single automatic deploy that does `npm install`

**Comment by israelidanny** [comment]
Minor versions often introduce small backward compatibility breaks.

**Comment by jquense** [comment]
the caret doesn't jump major versions.  and minor versions shouldn't introduce breaking change. if we don't trust semver I'm not sure why allowing patch versions would be better....

**Comment by jquense** [comment]
which is to say I get the concern, but having to babysit every dependency is no fun either and we already spend to much time doing it for all the pre 1.0.0 packages (which don't bump minor versions with the caret)

**Comment by taion** [comment]
Also, this package has no direct dependencies, so those are only dev dependencies, which shouldn't break you anyway.

**Comment by AlexKVal** [comment]
@israelidanny could you please provide more details ?
Ot better, could you point out where exactly problem is ?
There is something happened that became the cause of your question.
What is it ? We will try to help :cherries:

**Comment by israelidanny** [comment]
Hmm. You guys are right.

I had bad experiences with minor versions introducing unexpected behavior before, but according to the  `semver` spec (in which I peeked again right now), they're not supposed to.
