### ISSUE TITLE
Deprecated RouterModalTrigger in react-bootstrap 0.24

### ISSUE THREAD

**Issue by ppascher** [react-bootstrap/react-router-bootstrap#97]
I get an error message using the latest react-bootstrap 0.24.0 with react-router-bootstrap 0.17.2:

"[Error: Cannot find module 'react-bootstrap/lib/ModalTrigger' from '/projects/intranet/frontend/node_modules/react-router-bootstrap/lib"

It seems like ModalTrigger is gone for good as was already the case in a minor 0.23.x release before it was fixed.

**Comment by taion** [comment]
Will remove in next release.

**Comment by prattsj** [comment]
+1
